Repository NationalSecurityAgency/emissary, pull requests merged in 2020-12, with the labels that each got.

#91 update logging and codec dep versions
  pom.xml
Labels: dependencies

#93 remove ruby console
  README.md
  emissary
  pom.xml
  src/main/java/emissary/scripting/RubyConsole.java
  src/main/java/emissary/server/mvc/ConsoleAction.java
  src/main/resources/emissary/scripting/RubyConsole.cfg
  src/main/resources/public/index.html
  src/main/resources/public/js/emissary.js
  src/main/resources/public/js/lib/MochiKit/Async.js
  src/main/resources/public/js/lib/MochiKit/Base.js
  src/main/resources/public/js/lib/MochiKit/Color.js
  src/main/resources/public/js/lib/MochiKit/DOM.js
  src/main/resources/public/js/lib/MochiKit/DateTime.js
  src/main/resources/public/js/lib/MochiKit/Format.js
  src/main/resources/public/js/lib/MochiKit/Iter.js
  src/main/resources/public/js/lib/MochiKit/Logging.js
  src/main/resources/public/js/lib/MochiKit/LoggingPane.js
  src/main/resources/public/js/lib/MochiKit/MochiKit.js
  src/main/resources/public/js/lib/MochiKit/MockDOM.js
  src/main/resources/public/js/lib/MochiKit/Signal.js
  src/main/resources/public/js/lib/MochiKit/Test.js
  src/main/resources/public/js/lib/MochiKit/Visual.js
  src/main/resources/public/js/lib/MochiKit/__package__.js
  src/main/resources/templates/console.mustache
  src/test/java/emissary/scripting/RubyConsoleTest.java
  src/test/java/emissary/server/mvc/ConsoleActionTest.java
Labels: security

#94 remove some old dependencies
  pom.xml
Labels: dependencies

#98 Update README.md and add SECURITY.md
  README.md
  SECURITY.md
Labels: security

#92 update emissary to use webjars
  pom.xml
  src/main/resources/public/css/emissary.css
  src/main/resources/public/index.html
  src/main/resources/public/js/emissary_nav.js
  src/main/resources/templates/document_form.mustache
  src/main/resources/templates/document_submit.mustache
  src/main/resources/templates/dump_directory.mustache
  src/main/resources/templates/environment.mustache
  src/main/resources/templates/namespace.mustache
  src/main/resources/templates/threaddumps.mustache
Labels: dependencies, security

#101 Bump dep.jetty.version and dep.jersey.version
  pom.xml
Labels: dependencies, security
