Repository NationalSecurityAgency/emissary, pull requests merged in 2021-05, with the labels that each got.

#151 update to jersey 2.34
  pom.xml
Labels: dependencies, security

#147 Updating pom.xml with minor dependency updates
  pom.xml
Labels: dependencies, discussion

#149 remove relay hosts and parent/child node concept
  src/main/java/emissary/core/HDMobileAgent.java
  src/main/java/emissary/core/MobileAgent.java
  src/main/java/emissary/directory/DirectoryAdapter.java
  src/main/java/emissary/directory/DirectoryObserverManager.java
  src/main/java/emissary/directory/DirectoryPlace.java
  src/main/java/emissary/directory/DirectoryXmlContainer.java
  src/main/java/emissary/directory/HeartbeatManager.java
  src/main/java/emissary/directory/IDirectoryPlace.java
  src/main/java/emissary/directory/IRemoteDirectory.java
  src/main/java/emissary/directory/RelayObserver.java
  src/main/java/emissary/server/mvc/adapters/DirectoryAdapter.java
  src/main/java/emissary/server/mvc/internal/AddChildDirectoryAction.java
  src/main/java/emissary/server/mvc/internal/FailDirectoryAction.java
  src/test/java/emissary/directory/FTestPeerDirectoryPlace.java
  src/test/java/emissary/server/mvc/internal/FailDirectoryActionTest.java
Labels: security

#155 remove Create/RegisterPlaceAction
  src/main/java/emissary/admin/Startup.java
  src/main/java/emissary/server/mvc/adapters/PlaceStarterAdapter.java
  src/main/java/emissary/server/mvc/internal/CreatePlaceAction.java
  src/main/java/emissary/server/mvc/internal/RegisterPlaceAction.java
  src/test/java/emissary/server/mvc/internal/CreatePlaceActionTest.java
  src/test/java/emissary/server/mvc/internal/RegisterPlaceActionTest.java
Labels: security
