Repository NationalSecurityAgency/emissary, pull requests merged in 2021-04, with the labels that each got.

#127 add the jetty csrf filter to EmissaryServer
  src/main/java/emissary/client/EmissaryClient.java
  src/main/java/emissary/command/HttpCommand.java
  src/main/java/emissary/command/ServerCommand.java
  src/main/java/emissary/command/ServiceCommand.java
  src/main/java/emissary/command/StopCommand.java
  src/main/java/emissary/directory/HeartbeatManager.java
  src/main/java/emissary/server/EmissaryServer.java
  src/main/java/emissary/server/api/HealthCheckAction.java
  src/main/java/emissary/server/api/Pause.java
  src/main/java/emissary/server/api/Shutdown.java
  src/main/java/emissary/server/mvc/PauseAction.java
  src/main/java/emissary/server/mvc/ShutdownAction.java
  src/main/java/emissary/server/mvc/adapters/DirectoryAdapter.java
  src/main/java/emissary/server/mvc/adapters/HeartbeatAdapter.java
  src/main/java/emissary/server/mvc/adapters/MoveToAdapter.java
  src/main/java/emissary/server/mvc/adapters/PlaceStarterAdapter.java
  src/main/java/emissary/server/mvc/adapters/WorkSpaceAdapter.java
  src/main/resources/public/js/emissary_nav.js
  src/main/resources/templates/pause.mustache
  src/main/resources/templates/server_message.mustache
  src/main/resources/templates/shutdown.mustache
  src/main/resources/templates/unpause.mustache
Labels: framework, integration, security

#133 upgrade to guava 30.0-jre
  pom.xml
Labels: dependencies, security

#132 refactor getEndpoint to getFullUrl
  src/main/java/emissary/command/HttpCommand.java
Labels: tech-debt

#142 Update to commons-pool2
  pom.xml
  src/main/java/emissary/core/AgentPoolHealthCheck.java
  src/main/java/emissary/core/MobileAgent.java
  src/main/java/emissary/pool/AgentPool.java
  src/main/java/emissary/pool/MobileAgentFactory.java
  src/main/java/emissary/server/api/Pool.java
Labels: dependencies
