Repository NationalSecurityAgency/emissary, pull requests merged in 2021-03, with the labels that each got.

#123 remove ConfigFile action and remote capability from ConfigUtil
  src/main/java/emissary/config/ConfigUtil.java
  src/main/java/emissary/server/mvc/internal/ConfigFileAction.java
  src/test/java/emissary/server/mvc/internal/ConfigFileActionTest.java
Labels: security

#119 added try-with-resources to test util
  src/main/java/emissary/util/io/UnitTestFileUtils.java
Labels: tech-debt

#112 Update Docker files, removed Jenkins files, added Docker to README
  Docker_compose_test_script.sh
  Dockerfile
  Dockerfile-test-feeder
  Jenkinsfile
  Jenkinsfile_package
  README.md
  README_DOCKER.md
  contrib/docker/docker-compose.yml
  docker-compose.test.yml
  pom.xml
Labels: tech-debt

#87 Resource Watcher Fix
  src/main/java/emissary/core/MetricsFormatter.java
  src/main/java/emissary/core/ResourceWatcher.java
  src/test/java/emissary/core/ResourceWatcherTest.java
Labels: bug
