Repository NationalSecurityAgency/emissary, pull requests merged in 2022-12, with the labels that each got.

#204 Large data support
  pom.xml
  src/main/java/emissary/core/BaseDataObject.java
  src/main/java/emissary/core/IBaseDataObject.java
  src/main/java/emissary/core/IBaseDataObjectHelper.java
  src/main/java/emissary/core/channels/AbstractSeekableByteChannel.java
  src/main/java/emissary/core/channels/FileChannelFactory.java
  src/main/java/emissary/core/channels/FillChannelFactory.java
  src/main/java/emissary/core/channels/ImmutableChannelFactory.java
  src/main/java/emissary/core/channels/InMemoryChannelFactory.java
  src/main/java/emissary/core/channels/InputStreamChannelFactory.java
  src/main/java/emissary/core/channels/InputStreamFactory.java
  src/main/java/emissary/core/channels/SeekableByteChannelFactory.java
  src/main/java/emissary/core/channels/SeekableByteChannelHelper.java
  src/main/java/emissary/kff/ChecksumCalculator.java
  src/main/java/emissary/kff/KffChain.java
  src/main/java/emissary/kff/KffDataObjectHandler.java
  src/main/java/emissary/kff/Ssdeep.java
  src/main/java/emissary/output/DropOffPlace.java
  src/main/java/emissary/output/filter/JsonOutputFilter.java
  src/main/java/emissary/place/KffHashPlace.java
  src/main/java/emissary/place/MultiFileServerPlace.java
  src/main/java/emissary/util/DisposeHelper.java
  src/main/java/emissary/util/PlaceComparisonHelper.java
  src/main/resources/emissary/place/KffHashPlace.cfg
  src/test/java/emissary/core/BaseDataObjectTest.java
  src/test/java/emissary/core/IBaseDataObjectHelperTest.java
  src/test/java/emissary/core/channels/AbstractSeekableByteChannelTest.java
  src/test/java/emissary/core/channels/ChannelTestHelper.java
  src/test/java/emissary/core/channels/FileChannelFactoryTest.java
  src/test/java/emissary/core/channels/FillChannelFactoryTest.java
  src/test/java/emissary/core/channels/ImmutableChannelFactoryTest.java
  src/test/java/emissary/core/channels/InMemoryChannelFactoryTest.java
  src/test/java/emissary/core/channels/InputStreamChannelFactoryTest.java
  src/test/java/emissary/core/channels/SeekableByteChannelHelperTest.java
  src/test/java/emissary/kff/ChecksumCalculatorTest.java
  src/test/java/emissary/util/DisposeHelperTest.java
  src/test/java/emissary/util/PlaceComparisonHelperTest.java
  src/test/java/emissary/util/PlaceComparisonHelperTestPlace.java
Labels: feature, framework, tested

#361 Large data - follow-up/phase 2 work
  src/main/java/emissary/core/BaseDataObject.java
  src/main/java/emissary/core/IBaseDataObjectHelper.java
  src/main/java/emissary/core/channels/AbstractSeekableByteChannel.java
  src/main/java/emissary/core/channels/FileChannelFactory.java
  src/main/java/emissary/core/channels/FillChannelFactory.java
  src/main/java/emissary/core/channels/InputStreamChannelFactory.java
  src/main/java/emissary/core/channels/SeekableByteChannelHelper.java
  src/main/java/emissary/util/DisposeHelper.java
  src/main/java/emissary/util/PlaceComparisonHelper.java
  src/test/java/emissary/core/BaseDataObjectTest.java
  src/test/java/emissary/core/IBaseDataObjectHelperTest.java
  src/test/java/emissary/core/channels/AbstractSeekableByteChannelTest.java
  src/test/java/emissary/core/channels/FileChannelFactoryTest.java
  src/test/java/emissary/core/channels/FillChannelFactoryTest.java
  src/test/java/emissary/core/channels/ImmutableChannelFactoryTest.java
  src/test/java/emissary/core/channels/InputStreamChannelFactoryTest.java
  src/test/java/emissary/core/channels/SeekableByteChannelHelperTest.java
  src/test/java/emissary/kff/ChecksumCalculatorTest.java
  src/test/java/emissary/util/PlaceComparisonHelperTest.java
  src/test/java/emissary/util/TestMinimalServiceProviderPlace.java
Labels: enhancement, needs testing

#324 sonarlint :: more cleanup
  src/main/java/emissary/core/Namespace.java
  src/main/java/emissary/core/Stage.java
  src/main/java/emissary/directory/IRemoteDirectory.java
  src/main/java/emissary/directory/WildcardEntry.java
  src/main/java/emissary/parser/DecomposedSession.java
  src/main/java/emissary/parser/InputSession.java
  src/main/java/emissary/pickup/WorkBundle.java
  src/main/java/emissary/roll/RollManager.java
  src/main/java/emissary/server/mvc/adapters/WorkSpaceAdapter.java
  src/main/java/emissary/util/JMXUtil.java
  src/main/java/emissary/util/JavaCharSet.java
  src/main/java/emissary/util/io/ResourceReader.java
Labels: tech-debt, minor

#325 sonarlint :: rollablefileoutputstream
  src/main/java/emissary/util/roll/RollableFileOutputStream.java
Labels: tech-debt, minor

#342 sonarlint :: more cleanup
  src/main/java/emissary/kff/ChecksumCalculator.java
  src/main/java/emissary/kff/ChecksumResults.java
  src/main/java/emissary/output/filter/DataFilter.java
  src/main/java/emissary/parser/DataByteArraySlicer.java
  src/main/java/emissary/parser/DataByteBufferSlicer.java
  src/main/java/emissary/place/CoordinationPlace.java
Labels: tech-debt, minor

#350 sonarlint :: EmissaryClient field names and minor updates
  src/main/java/emissary/client/EmissaryClient.java
Labels: tech-debt, minor

#367 attempting to consolidate constants into classes
  src/main/java/emissary/command/WhatCommand.java
  src/main/java/emissary/core/Form.java
  src/main/java/emissary/core/constants/Configurations.java
  src/main/java/emissary/core/constants/Parameters.java
  src/main/java/emissary/output/DropOffUtil.java
  src/main/java/emissary/output/filter/DataFilter.java
  src/main/java/emissary/pickup/PickUpPlace.java
  src/main/java/emissary/pickup/file/FilePickUpClient.java
  src/main/java/emissary/place/CoordinationPlace.java
  src/main/java/emissary/place/MultiFileUnixCommandPlace.java
  src/main/java/emissary/place/ServiceProviderPlace.java
  src/main/java/emissary/place/UnixCommandPlace.java
  src/main/java/emissary/place/sample/ToLowerPlace.java
  src/main/java/emissary/place/sample/ToUpperPlace.java
  src/main/java/emissary/transform/HtmlEscapePlace.java
  src/main/java/emissary/transform/JavascriptEscapePlace.java
  src/main/java/emissary/transform/JsonEscapePlace.java
  src/main/java/emissary/util/CharsetUtil.java
  src/main/java/emissary/util/DataUtil.java
  src/main/java/emissary/util/MetadataDictionaryUtil.java
  src/main/java/emissary/util/shell/Executrix.java
  src/main/java/emissary/util/web/HttpPostParameters.java
  src/test/java/emissary/core/FTestMovingAgent.java
  src/test/java/emissary/output/DropOffUtilTest.java
  src/test/java/emissary/pickup/file/FilePickUpClientTest.java
  src/test/java/emissary/place/FTestCoordinatePlace.java
  src/test/java/emissary/place/FTestSkippingCoordinationPlace.java
  src/test/java/emissary/transform/HtmlEscapePlaceTest.java
  src/test/java/emissary/util/DataUtilTest.java
  src/test/java/emissary/util/LineTokenizerTest.java
Labels: discussion, tech-debt, rebase

#377 sonarlint :: Remove duplicate log configuration code from EnvCommand
  src/main/java/emissary/Emissary.java
  src/main/java/emissary/command/EnvCommand.java
Labels: tech-debt

#339 sonarlint :: utils/io
  src/main/java/emissary/util/io/FastStringBuffer.java
  src/main/java/emissary/util/io/FileFind.java
  src/main/java/emissary/util/io/FileManipulator.java
  src/main/java/emissary/util/io/ResourceReader.java
  src/main/java/emissary/util/io/SocketUtils.java
Labels: tech-debt, minor

#341 sonarlint :: more utils
  src/main/java/emissary/util/search/ByteTokenizer.java
  src/main/java/emissary/util/shell/ReadOutputBuffer.java
  src/main/java/emissary/util/web/Url.java
  src/main/java/emissary/util/web/UrlData.java
Labels: tech-debt, minor

#326 sonarlint :: serviceconfigguide
  src/main/java/emissary/config/ServiceConfigGuide.java
Labels: tech-debt, minor

#340 sonarlint :: util
  src/main/java/emissary/util/ByteUtil.java
  src/main/java/emissary/util/CaseInsensitiveMap.java
  src/main/java/emissary/util/ClassComparator.java
  src/main/java/emissary/util/ClassLookupCache.java
  src/main/java/emissary/util/ConstructorLookupCache.java
  src/main/java/emissary/util/CounterSet.java
  src/main/java/emissary/util/DataUtil.java
  src/main/java/emissary/util/Entropy.java
  src/main/java/emissary/util/HtmlEntityMap.java
  src/main/java/emissary/util/SizeUtil.java
  src/main/java/emissary/util/TypeEngine.java
Labels: tech-debt, minor

#351 Create lightweight alpine Dockerfile
  DEVELOPING.md
  contrib/docker/Dockerfile.alpine
Labels: minor
