Repository NationalSecurityAgency/emissary, pull requests merged in 2022-03, with the labels that each got.

#205 (Minor) Update GitHub actions workflow
  .github/workflows/maven.yml
  .gitignore
  README.md
Labels: tech-debt

#177 #176: removed several obsolete/unused classes
  src/main/java/emissary/core/AggregateObject.java
  src/main/java/emissary/core/Facet.java
  src/main/java/emissary/core/IAggregator.java
  src/main/java/emissary/directory/DirectoryPlace.java
  src/main/java/emissary/directory/IDirectoryPlace.java
  src/main/java/emissary/directory/ItineraryFace.java
  src/main/java/emissary/directory/ItineraryFaceImpl.java
  src/main/java/emissary/directory/ItineraryFacet.java
  src/main/java/emissary/directory/JSAcceptFacet.java
  src/main/java/emissary/place/ServiceProviderPlace.java
  src/test/java/emissary/core/AggregateObjectTest.java
  src/test/java/emissary/directory/ItineraryFacetTest.java
  src/test/java/emissary/directory/JSAcceptFacetTest.java
Labels: integration

#194 Cleanup of readme and creation of developing guide
  DEVELOPING.md
  README.md
  SECURITY.md
Labels: documentation
