Repository NationalSecurityAgency/emissary, pull requests merged in 2022-06, with the labels that each got.

#254 upgrade to commons-lang3
  pom.xml
  src/main/java/emissary/command/ServiceCommand.java
  src/main/java/emissary/config/ServiceConfigGuide.java
  src/main/java/emissary/core/BaseDataObject.java
  src/main/java/emissary/directory/DirectoryEntryList.java
  src/main/java/emissary/id/TikaFilePlace.java
  src/main/java/emissary/output/filter/AbstractFilter.java
  src/main/java/emissary/output/filter/AbstractRollableFilter.java
  src/main/java/emissary/output/io/DateStampFilenameGenerator.java
  src/main/java/emissary/place/Main.java
  src/main/java/emissary/server/mvc/internal/DeregisterPlaceAction.java
  src/main/java/emissary/server/mvc/internal/FailDirectoryAction.java
  src/main/java/emissary/server/mvc/internal/RegisterPeerAction.java
  src/main/java/emissary/server/mvc/internal/WorkBundleCompletedAction.java
  src/main/java/emissary/server/mvc/internal/WorkSpaceClientSpaceTakeAction.java
  src/main/java/emissary/test/core/ExtractionTest.java
  src/main/java/emissary/util/FlexibleDateTimeParser.java
  src/main/java/emissary/util/TimeUtil.java
  src/test/java/emissary/kff/KffMemcachedTest.java
  src/test/java/emissary/output/filter/JsonOutputFilterTest.java
Labels: dependencies

#261 add git properties file to build dir #879
  pom.xml
Labels: dependencies

#258 (Minor) Refactor log reading during unit tests
  src/main/java/emissary/test/core/LogbackCapture.java
  src/test/java/emissary/config/ConfigUtilTest.java
Labels: tech-debt, integration

#253 test jar
  pom.xml
  src/main/java/emissary/test/core/package-info.java
  src/test/java/emissary/test/core/ExtractionTest.java
  src/test/java/emissary/test/core/FunctionalTest.java
  src/test/java/emissary/test/core/IdentificationTest.java
  src/test/java/emissary/test/core/LogbackCapture.java
  src/test/java/emissary/test/core/UnitTest.java
Labels: framework, integration
