Repository NationalSecurityAgency/emissary, pull requests merged in 2022-04, with the labels that each got.

#208 error prone updates - add missing overrides
  pom.xml
  src/main/java/emissary/Emissary.java
  src/main/java/emissary/client/response/BaseResponseEntity.java
  src/main/java/emissary/client/response/PlacesResponseEntity.java
  src/main/java/emissary/command/AgentsCommand.java
  src/main/java/emissary/command/BaseCommand.java
  src/main/java/emissary/command/EnvCommand.java
  src/main/java/emissary/command/FeedCommand.java
  src/main/java/emissary/command/PoolCommand.java
  src/main/java/emissary/command/ServerCommand.java
  src/main/java/emissary/command/StopCommand.java
  src/main/java/emissary/command/TopologyCommand.java
  src/main/java/emissary/command/WhatCommand.java
  src/main/java/emissary/config/ServiceConfigGuide.java
  src/main/java/emissary/core/HDMobileAgent.java
  src/main/java/emissary/core/TimedResource.java
  src/main/java/emissary/output/roller/JournaledCoalescer.java
  src/main/java/emissary/test/core/UnitTest.java
  src/test/java/emissary/command/FeedCommandIT.java
  src/test/java/emissary/command/converter/PathExistsReadableNoTrailingSlashConverterTest.java
  src/test/java/emissary/command/converter/PriorityDirectoryConverterTest.java
  src/test/java/emissary/directory/DirectoryPlaceTest.java
  src/test/java/emissary/output/filter/XmlOutputFilterTest.java
  src/test/java/emissary/place/CoordinationPlaceTest.java
  src/test/java/emissary/server/api/ApiUtilsTest.java
  src/test/java/emissary/server/api/PeersIT.java
  src/test/java/emissary/server/mvc/internal/DeregisterPlaceActionTest.java
  src/test/java/emissary/server/mvc/internal/FailDirectoryActionTest.java
  src/test/java/emissary/server/mvc/internal/HeartbeatActionTest.java
  src/test/java/emissary/server/mvc/internal/RegisterPeerActionTest.java
  src/test/java/emissary/server/mvc/internal/WorkBundleCompletedActionTest.java
  src/test/java/emissary/server/mvc/internal/WorkSpaceClientSpaceTakeActionTest.java
Labels: tech-debt

#199 Update Dropwizard Metrics library to 4.2.9
  pom.xml
  src/main/java/emissary/core/MetricsManager.java
Labels: dependencies, tech-debt

#210 error prone updates - update tests based on rules TryFailRefactoring,…
  src/test/java/emissary/EmissaryTest.java
  src/test/java/emissary/command/RunCommandIT.java
  src/test/java/emissary/command/ServerCommandIT.java
  src/test/java/emissary/config/ConfigUtilTest.java
  src/test/java/emissary/config/ServiceConfigGuideTest.java
  src/test/java/emissary/core/BaseDataObjectTest.java
  src/test/java/emissary/core/FTestMovingAgent.java
  src/test/java/emissary/core/FactoryTest.java
  src/test/java/emissary/core/NamespaceTest.java
  src/test/java/emissary/kff/ChecksumCalculatorTest.java
  src/test/java/emissary/kff/ChecksumResultsTest.java
  src/test/java/emissary/parser/InputSessionTest.java
  src/test/java/emissary/parser/SimpleNioParserTest.java
  src/test/java/emissary/parser/SimpleParserTest.java
  src/test/java/emissary/pickup/WorkBundleTest.java
  src/test/java/emissary/place/MainTest.java
  src/test/java/emissary/place/ServiceProviderPlaceTest.java
  src/test/java/emissary/util/MetadataDictionaryUtilTest.java
  src/test/java/emissary/util/search/ByteMatcherTest.java
  src/test/java/emissary/util/web/UrlTest.java
  src/test/java/emissary/util/xml/JDOMUtilTest.java
Labels: tech-debt

#218 dependabot: update jackson to 2.12.6 and jackson-databind to 2.12.6.1
  pom.xml
Labels: dependencies, security

#192 Fixing LineTokenizer.nextTokenBytes to move the index to the end
  src/main/java/emissary/util/LineTokenizer.java
  src/test/java/emissary/util/LineTokenizerTest.java
Labels: tech-debt, integration

#220 multiple dependency updates, remove rhino
  pom.xml
Labels: dependencies
