Repository NationalSecurityAgency/emissary, pull requests merged in 2023-10, with the labels that each got.

#594 Add helper to find preferredData by regex and add to Analyzer
  src/main/java/emissary/analyze/Analyzer.java
  src/main/java/emissary/core/IBaseDataObjectHelper.java
  src/test/java/emissary/core/IBaseDataObjectHelperTest.java
Labels: integration

#588 cleanup some jetty references
  src/main/java/emissary/client/EmissaryClient.java
  src/main/java/emissary/client/EmissaryResponse.java
  src/test/java/emissary/test/core/junit5/FunctionalTest.java
Labels: tech-debt, integration

#557 remove deprecated constructor from startup
  src/main/java/emissary/admin/Startup.java
Labels: tech-debt

#559 remove deprecated ibdo methods
  src/main/java/emissary/core/BaseDataObject.java
  src/main/java/emissary/core/IBaseDataObject.java
Labels: tech-debt, integration

#561 remove deprecated stop command
  src/main/java/emissary/Emissary.java
  src/main/java/emissary/command/StopCommand.java
Labels: tech-debt

#562 remove deprecated droppoffutil methods
  src/main/java/emissary/output/DropOffUtil.java
  src/test/java/emissary/output/DropOffUtilTest.java
Labels: tech-debt, integration

#578 move UnitTestFileUtils to test jar
  src/test/java/emissary/util/io/UnitTestFileUtils.java
Labels: tech-debt

#565 remove deprecated parserfactory methods
  src/main/java/emissary/parser/ParserFactory.java
  src/main/java/emissary/pickup/PickUpPlace.java
Labels: tech-debt, integration

#291 io :: remove deprecated observer from the roller framework
  src/main/java/emissary/roll/RollManager.java
  src/main/java/emissary/roll/Roller.java
  src/test/java/emissary/roll/RollManagerTest.java
  src/test/java/emissary/roll/RollableTest.java
  src/test/java/emissary/roll/RollerTest.java
Labels: major

#538 Identify invalid IBDO data/array modifications.
  src/main/config/emissary.core.SafeUsageChecker.cfg
  src/main/java/emissary/core/BaseDataObject.java
  src/main/java/emissary/core/IBaseDataObject.java
  src/main/java/emissary/core/SafeUsageChecker.java
  src/main/java/emissary/place/ServiceProviderPlace.java
  src/test/java/emissary/core/BaseDataObjectTest.java
  src/test/java/emissary/core/SafeUsageCheckerTest.java
  src/test/java/emissary/test/core/junit5/LogbackTester.java
Labels: feature

#599 bump slf4j to 2+ and logback to 1.3+
  pom.xml
Labels: dependencies

#601 add run method to Pausable
  src/main/java/emissary/core/Pausable.java
Labels: tech-debt

#591 Replace Super Linter with Mega Linter
  .github/workflows/linter.yaml
Labels: CI/CD

#602 fix linter warns/errors in yml files
  .github/linters/.markdown-lint.yml
  .github/linters/.yaml-lint.yml
  .github/workflows/cherrypick.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/create-patch-branch.yml
  .github/workflows/dependency-review.yml
  .github/workflows/linter.yaml
  .github/workflows/maven-ci.yml
  .github/workflows/maven-publish.yml
  .github/workflows/maven-release.yml
  .github/workflows/maven-version.yml
  .gitignore
  contrib/docker/.hadolint.yaml
  contrib/docker/docker-compose.yml
  contrib/elasticsearch/filebeat.agents.docker.yml
  contrib/elasticsearch/sample_objectMetrics-filebeat-prospector.yml
Labels: tech-debt

#603 Correct maven CI badge in README.md
  README.md
Labels: CI/CD

#604 Remove object metrics
  contrib/elasticsearch/sample_objectMetrics-filebeat-prospector.yml
  src/main/config/emissary.output.DropOffPlace.cfg
  src/main/config/logback.xml
  src/main/java/emissary/output/DropOffPlace.java
  src/main/resources/emissary/output/DropOffPlace.cfg
  src/test/java/emissary/output/DropOffPlaceTest.java
Labels: tech-debt

#610 SafeUsageChecker no longer logs warning for routine/expected condition
  src/main/java/emissary/core/SafeUsageChecker.java
Labels: tech-debt

#596 Modified KffDataObjectHandler.hash(..) method so it explicitly replaces IBDO params it generates.
  src/main/java/emissary/core/BaseDataObject.java
  src/main/java/emissary/core/IBaseDataObject.java
  src/main/java/emissary/kff/KffDataObjectHandler.java
  src/test/java/emissary/kff/KffDataObjectHandlerTest.java
Labels: priority

#605 Reverted KffFile back to using RandomAccessFile for file I/O, but now synchronizing access to its use
  src/main/java/emissary/kff/KffFile.java
  src/test/java/emissary/kff/KffFileTest.java
Labels: priority

#612 Update DateFilterFilenameGeneratorTest to JUnit 5
  src/test/java/emissary/output/io/DateFilterFilenameGeneratorTest.java
Labels: test-only

#611 Ban log4j and javax.servlet dependencies
  pom.xml
Labels: feature
