Repository NationalSecurityAgency/emissary, pull requests merged in 2023-02, with the labels that each got.

#393 Move position update during read up to AbstractSeekableByteChannel
  src/main/java/emissary/core/channels/AbstractSeekableByteChannel.java
  src/main/java/emissary/core/channels/FileChannelFactory.java
  src/main/java/emissary/core/channels/FillChannelFactory.java
  src/main/java/emissary/core/channels/InputStreamChannelFactory.java
  src/test/java/emissary/core/channels/AbstractSeekableByteChannelTest.java
  src/test/java/emissary/core/channels/FileChannelFactoryTest.java
Labels: bug

#411 Simplify AbstractSeekableByteChannel by right-sizing the provided byteBuffer
  src/main/java/emissary/core/channels/AbstractSeekableByteChannel.java
  src/main/java/emissary/core/channels/FileChannelFactory.java
  src/main/java/emissary/core/channels/FillChannelFactory.java
  src/main/java/emissary/core/channels/InputStreamChannelFactory.java
  src/main/java/emissary/core/channels/SeekableByteChannelHelper.java
  src/test/java/emissary/core/IBaseDataObjectDiffHelperTest.java
  src/test/java/emissary/core/channels/AbstractSeekableByteChannelTest.java
  src/test/java/emissary/core/channels/SeekableByteChannelHelperTest.java
Labels: enhancement

#408 bump guava to 31.1
  pom.xml
Labels: dependencies

#396 Remove javadoc footer option to address build warnings
  pom.xml
Labels: tech-debt

#414 Improve test coverage for SeekableByteChannelHelper.
  src/test/java/emissary/core/channels/SeekableByteChannelHelperTest.java
Labels: tech-debt

#400 sonarlint :: remove the last of new FileInputStream
  src/main/java/emissary/kff/KffChainLoader.java
  src/main/java/emissary/kff/KffFile.java
  src/main/java/emissary/kff/KffQuincyFile.java
  src/main/java/emissary/kff/Ssdeep.java
  src/main/java/emissary/util/Hexl.java
Labels: tech-debt

#398 sonarlint :: faststringbuffer
  src/main/java/emissary/util/io/FastStringBuffer.java
Labels: tech-debt

#397 sonarlint :: cleanup directory package
  src/main/java/emissary/directory/DirectoryAdapter.java
  src/main/java/emissary/directory/DirectoryEntry.java
  src/main/java/emissary/directory/DirectoryEntryList.java
  src/main/java/emissary/directory/DirectoryEntryMap.java
  src/main/java/emissary/directory/DirectoryObserverManager.java
  src/main/java/emissary/directory/DirectoryXmlContainer.java
  src/main/java/emissary/directory/EmissaryNode.java
  src/main/java/emissary/directory/HeartbeatManager.java
  src/main/java/emissary/directory/IRemoteDirectory.java
Labels: tech-debt

#416 2129 Add creation of test jar sources and javadoc artifacts for deplo…
  pom.xml
Labels: feature

#412 Create SegmentChannelFactory.
  src/main/java/emissary/core/channels/SegmentChannelFactory.java
  src/test/java/emissary/core/channels/SegmentChannelFactoryTest.java
Labels: enhancement

#409 sonarlint :: jni package
  src/main/java/emissary/jni/IJniRepositoryPlace.java
  src/main/java/emissary/jni/JNI.java
  src/main/java/emissary/jni/JniRepositoryPlace.java
Labels: tech-debt

#404 Add maven dependency version reports
  DEVELOPING.md
  pom.xml
Labels: dependencies, documentation
