Repository NationalSecurityAgency/emissary, pull requests merged in 2023-05, with the labels that each got.

#477 exclude helm repo from super lint
  .github/workflows/super-linter.yaml
Labels: CI/CD

#474 call quit for the ResourceWatcher and remove instance of RollManager …
  src/main/java/emissary/core/ResourceWatcher.java
  src/main/java/emissary/pickup/file/FilePickUpPlace.java
  src/main/java/emissary/roll/RollManager.java
  src/main/java/emissary/server/EmissaryServer.java
Labels: bug

#469 Add an AgentEmitter class to output agent status
  src/main/config/emissary.roll.RollManager.cfg
  src/main/java/emissary/metrics/AgentsEmitter.java
Labels: feature

#465 Fix KeywordScanner case insensitive search
  src/main/java/emissary/util/search/KeywordScanner.java
  src/test/java/emissary/util/search/KeywordScannerTest.java
Labels: bug

#480 Only output version for version command and server startup
  src/main/java/emissary/Emissary.java
Labels: tech-debt

#405 Non impact full Plugin updates
  README.md
  pom.xml
Labels: dependencies

#485 remove isInUse check from HDMobileAgent toString()
  src/main/java/emissary/core/HDMobileAgent.java
  src/main/java/emissary/core/MobileAgent.java
Labels: bug

#483 Add BUILD_TIMESTAMP property back in pom for version command
  pom.xml
Labels: bug

#486 add test for MobileAgent typeLookup and handle null Stage name
  src/main/java/emissary/core/Stage.java
  src/test/java/emissary/core/MobileAgentTest.java
  src/test/java/emissary/core/StageTest.java
Labels: tech-debt
