Repository NationalSecurityAgency/emissary, pull requests merged in 2023-06, with the labels that each got.

#482 update to surefire 3.1.0
  pom.xml
Labels: dependencies

#493 simple sonarlint/code clean-up in ExtractionTest
  src/test/java/emissary/test/core/ExtractionTest.java
Labels: tech-debt

#489 update MobileAgent isInUse method to use idle boolean
  src/main/java/emissary/core/HDMobileAgent.java
  src/main/java/emissary/core/MobileAgent.java
Labels: needs testing

#495 manage jetty deps using the jetty-bom
  pom.xml
Labels: dependencies
