Repository NationalSecurityAgency/emissary, pull requests merged in 2023-07, with the labels that each got.

#510 Updated LoggingPrintStream so it won't block application shutdown (targets master)
  src/main/java/emissary/util/io/LoggingPrintStream.java
Labels: bug, needs review

#252 java 11
  .github/workflows/maven.yml
  .gitignore
  DEVELOPING.md
  README.md
  pom.xml
Labels: dependencies, framework, priority, integration, major, milestone

#519 add new github actions for releasing, publishing, versioning, & patching
  .github/workflows/create-patch-branch.yml
  .github/workflows/maven-ci.yml
  .github/workflows/maven-publish.yml
  .github/workflows/maven-release.yml
  .github/workflows/maven-version.yml
  contrib/ci/detect-changes.sh
  pom.xml
Labels: milestone

#507 Small pom updates for compliance with maven repositories
  pom.xml
Labels: major, milestone

#503 Mockito 5
  pom.xml
Labels: dependencies

#512 Add 'CHECKSUM_CRC32' to the list of removed parameter keys.
  src/main/java/emissary/kff/KffDataObjectHandler.java
Labels: enhancement

#517 Lift convertHexDate from MsSqlJflex into TimeUtil
  src/main/java/emissary/util/TimeUtil.java
  src/test/java/emissary/util/TimeUtilTest.java
Labels: enhancement
