Repository NationalSecurityAgency/emissary, pull requests merged in 2023-11, with the labels that each got.

#616 Renamed 'equals' methods to 'matches' in DirectoryEntry to avoid confusion.
  src/main/java/emissary/directory/DirectoryEntry.java
  src/test/java/emissary/directory/DirectoryEntryTest.java
Labels: tech-debt

#615 Refactored Roller.java to use AtomicLong
  src/main/java/emissary/roll/Roller.java
Labels: tech-debt

#609 Add additional IBDO parameter diff options.
  src/main/java/emissary/core/DiffCheckConfiguration.java
  src/main/java/emissary/core/IBaseDataObjectDiffHelper.java
  src/test/java/emissary/core/DiffCheckConfigurationTest.java
  src/test/java/emissary/core/IBaseDataObjectDiffHelperTest.java
Labels: enhancement

#598 addressing unexpected place startups
  src/main/java/emissary/admin/Startup.java
  src/test/java/emissary/admin/StartupTest.java
  src/test/resources/emissary/admin/StartupTest.cfg
  src/test/resources/emissary/admin/emissary/directory/StartupTest.cfg
Labels: feature

#626 Fixed Initialization Race Condition in DisposeHelperTest
  src/test/java/emissary/util/DisposeHelperTest.java
Labels: test-only

#625 Update RegressionTest to hash alternate views instead of base64 converting.
  src/main/java/emissary/core/IBaseDataObjectXmlCodecs.java
  src/test/java/emissary/core/IBaseDataObjectXmlHelperTest.java
  src/test/java/emissary/test/core/junit5/RegressionTest.java
Labels: test-only

#620 Improve LogBackTester interface
  src/test/java/emissary/test/core/junit5/LogbackTester.java
  src/test/java/emissary/test/core/junit5/LogbackTesterTest.java
Labels: test-only

#628 Simple EmissaryServer Clean-up
  src/main/java/emissary/server/EmissaryServer.java
Labels: tech-debt
