Repository NationalSecurityAgency/emissary, pull requests merged in 2023-01, with the labels that each got.

#376 Removed unnecessary calls to loadFrom() in KffChainLoader
  src/main/java/emissary/kff/KffChainLoader.java
Labels: tech-debt

#384 Cleanup using try-with-resources in mvc.internal tests
  src/test/java/emissary/server/mvc/internal/DeregisterPlaceActionTest.java
  src/test/java/emissary/server/mvc/internal/FailDirectoryActionTest.java
  src/test/java/emissary/server/mvc/internal/HeartbeatActionTest.java
  src/test/java/emissary/server/mvc/internal/RegisterPeerActionTest.java
  src/test/java/emissary/server/mvc/internal/WorkBundleCompletedActionTest.java
  src/test/java/emissary/server/mvc/internal/WorkSpaceClientSpaceTakeActionTest.java
Labels: tech-debt

#383 Remove hasConfigErrors from ConfigUtil
  src/main/java/emissary/config/ConfigUtil.java
  src/test/java/emissary/config/ConfigUtilTest.java
Labels: tech-debt

#387 sonarlint :: cast long operands before assignment
  src/main/java/emissary/kff/KffFile.java
  src/main/java/emissary/output/DropOffUtil.java
  src/main/java/emissary/parser/ParserFactory.java
  src/main/java/emissary/util/WindowedSeekableByteChannel.java
Labels: tech-debt

#386 Refactor diff methods into a more cohesive structure
  src/main/java/emissary/core/DiffCheckConfiguration.java
  src/main/java/emissary/core/IBaseDataObjectDiffHelper.java
  src/main/java/emissary/core/IBaseDataObjectHelper.java
  src/main/java/emissary/util/PlaceComparisonHelper.java
  src/test/java/emissary/core/IBaseDataObjectDiffHelperTest.java
  src/test/java/emissary/core/IBaseDataObjectHelperTest.java
  src/test/java/emissary/util/PlaceComparisonHelperTest.java
Labels: enhancement

#390 Sanitize request parameters in RequestUtil
  src/main/java/emissary/server/mvc/adapters/RequestUtil.java
  src/test/java/emissary/server/mvc/adapters/RequestUtilTest.java
Labels: security

#391 update actions checkout to 3.3.0
  .github/workflows/codeql-analysis.yml
  .github/workflows/maven.yml
Labels: tech-debt
