Repository NationalSecurityAgency/emissary, pull requests merged in 2023-04, with the labels that each got.

#413 Add support for RegressionTest as a more comprehensive extension of ExtractionTest
  src/main/java/emissary/core/IBaseDataObjectXmlHelper.java
  src/test/java/emissary/core/IBaseDataObjectXmlHelperTest.java
  src/test/java/emissary/test/core/junit5/ExtractionTest.java
  src/test/java/emissary/test/core/junit5/InitialFinalFormFormat.java
  src/test/java/emissary/test/core/junit5/RegressionTest.java
  src/test/java/emissary/test/core/junit5/RegressionTestUtil.java
Labels: discussion, feature

#456 fix DateTimeFormatParser unchecked conversion build warning
  src/main/java/emissary/util/DateTimeFormatParser.java
Labels: tech-debt

#454 exclude javax.servlet-api and rely on jakarta.servlet-api
  pom.xml
Labels: dependencies

#455 address RegressionTestUtil javadoc warnings
  src/test/java/emissary/test/core/junit5/RegressionTestUtil.java
Labels: tech-debt

#458 create unique test file for RollManagerTest
  src/test/java/emissary/roll/RollManagerTest.java
  src/test/resources/emissary/roll/RollManagerTest.cfg
Labels: tech-debt

#449 Remove 'overrideConfigCompilerVersion' from formatter configuration
  pom.xml
Labels: tech-debt

#422 sonar :: remove unnecessary boxing/unboxing (bug)
  src/main/java/emissary/client/EmissaryClient.java
  src/main/java/emissary/server/EmissaryServer.java
  src/main/java/emissary/util/magic/MagicMath.java
  src/test/java/emissary/client/EmissaryClientTest.java
Labels: tech-debt

#426 sonar :: add synchronized to clear() and isInUse() methods in HDMobil…
  src/main/java/emissary/core/HDMobileAgent.java
Labels: tech-debt

#421 sonar :: update interrupt handling (bug)
  src/main/java/emissary/admin/Startup.java
  src/main/java/emissary/command/MonitorCommand.java
  src/main/java/emissary/core/MobileAgent.java
  src/main/java/emissary/core/Pausable.java
  src/main/java/emissary/core/ResourceWatcher.java
  src/main/java/emissary/output/DropOffUtil.java
  src/main/java/emissary/output/roller/JournaledCoalescer.java
  src/main/java/emissary/pickup/QueServer.java
  src/main/java/emissary/pickup/WorkSpace.java
  src/main/java/emissary/pickup/file/FileDataServer.java
  src/main/java/emissary/place/Main.java
  src/main/java/emissary/pool/AgentPool.java
  src/main/java/emissary/pool/MoveSpool.java
  src/main/java/emissary/roll/RollScheduledExecutor.java
  src/main/java/emissary/server/EmissaryServer.java
  src/main/java/emissary/util/WatcherThread.java
  src/main/java/emissary/util/shell/Executrix.java
Labels: needs testing

#466 update jetty to 9.4.51.v20230217
  pom.xml
Labels: dependencies, security

#463 Allow ByteMatcher to stop at a specified index
  src/main/java/emissary/util/search/ByteMatcher.java
  src/test/java/emissary/util/search/ByteMatcherTest.java
Labels: enhancement

#394 add dependency review action
  .github/workflows/dependency-review.yml
Labels: CI/CD

#468 minor touchups from strict mode addition
  src/main/java/emissary/admin/Startup.java
  src/main/java/emissary/command/ServerCommand.java
Labels: tech-debt

#369 Refactor Stage to be an enum (Closes #1877)
  src/main/java/emissary/core/MobileAgent.java
  src/main/java/emissary/core/Stage.java
  src/test/java/emissary/core/StageTest.java
Labels: framework

#382 Add super-linter github action
  .github/linters/.markdown-lint.yml
  .github/linters/.yaml-lint.yml
  .github/workflows/super-linter.yaml
Labels: CI/CD

#448 Built out command to list Emissary Directories
  src/main/java/emissary/Emissary.java
  src/main/java/emissary/client/response/Directory.java
  src/main/java/emissary/client/response/DirectoryList.java
  src/main/java/emissary/client/response/DirectoryResponseEntity.java
  src/main/java/emissary/command/DirectoryCommand.java
  src/main/java/emissary/server/api/Directories.java
  src/test/java/emissary/server/api/EmissaryApiTest.java
Labels: feature
