Repository NationalSecurityAgency/emissary, pull requests merged in 2023-12, with the labels that each got.

#624 add a watch thread to test for stuck places
  src/main/java/emissary/core/sentinel/Sentinel.java
  src/main/java/emissary/core/sentinel/protocols/Protocol.java
  src/main/java/emissary/core/sentinel/protocols/actions/Action.java
  src/main/java/emissary/core/sentinel/protocols/actions/Exit.java
  src/main/java/emissary/core/sentinel/protocols/actions/Kill.java
  src/main/java/emissary/core/sentinel/protocols/actions/Notify.java
  src/main/java/emissary/core/sentinel/protocols/actions/Recover.java
  src/main/java/emissary/core/sentinel/protocols/actions/Stop.java
  src/main/java/emissary/core/sentinel/protocols/rules/AllMaxTime.java
  src/main/java/emissary/core/sentinel/protocols/rules/AnyMaxTime.java
  src/main/java/emissary/core/sentinel/protocols/rules/Rule.java
  src/main/java/emissary/directory/EmissaryNode.java
  src/main/java/emissary/server/EmissaryServer.java
  src/main/resources/emissary/core/sentinel/Sentinel.cfg
  src/main/resources/emissary/core/sentinel/protocols/ProtocolSample.cfg
Labels: priority

#541 remove junit 4
  pom.xml
  src/test/java/emissary/test/core/ExtractionTest.java
  src/test/java/emissary/test/core/FunctionalTest.java
  src/test/java/emissary/test/core/IdentificationTest.java
  src/test/java/emissary/test/core/TestExtractionTest.java
  src/test/java/emissary/test/core/UnitTest.java
Labels: integration

#265 io :: updated JsonOutputFilter ignorelist
  src/main/java/emissary/output/filter/JsonOutputFilter.java
  src/main/resources/emissary/output/filter/JsonOutputFilter.cfg
  src/test/java/emissary/output/filter/JsonOutputFilterTest.java
Labels: integration, major

#568 remove deprecated runcommand and main-runner
  README.md
  pom.xml
  src/main/java/emissary/Emissary.java
  src/main/java/emissary/command/RunCommand.java
  src/main/java/emissary/id/SizeIdPlace.java
  src/main/java/emissary/id/UnixFilePlace.java
  src/main/java/emissary/output/DropOffPlace.java
  src/main/java/emissary/pickup/file/FilePickUpClient.java
  src/main/java/emissary/pickup/file/FilePickUpPlace.java
  src/main/java/emissary/place/CoordinationPlace.java
  src/main/java/emissary/place/Main.java
  src/main/java/emissary/place/MultiFileUnixCommandPlace.java
  src/main/java/emissary/place/ServiceProviderPlace.java
  src/main/java/emissary/place/UnixCommandPlace.java
  src/main/java/emissary/place/sample/DelayPlace.java
  src/main/java/emissary/place/sample/DevNullPlace.java
  src/main/java/emissary/place/sample/TemplatePlace.java
  src/main/java/emissary/place/sample/ToLowerPlace.java
  src/main/java/emissary/place/sample/ToUpperPlace.java
  src/main/java/emissary/transform/HtmlEscapePlace.java
  src/main/java/emissary/transform/JavascriptEscapePlace.java
  src/main/java/emissary/transform/JsonEscapePlace.java
  src/test/java/emissary/command/RunCommandIT.java
  src/test/java/emissary/place/MainTest.java
Labels: tech-debt, integration

#272 io :: updated AbstractFilter to use denylist
  src/main/java/emissary/output/filter/AbstractFilter.java
Labels: integration, major

#571 remove deprecated simpleparser
  src/main/java/emissary/parser/ParserFactory.java
  src/main/java/emissary/parser/SimpleParser.java
  src/main/resources/emissary/parser/ParserFactory.cfg
  src/test/java/emissary/parser/SessionProducerTest.java
  src/test/java/emissary/parser/SimpleNioParserTest.java
  src/test/java/emissary/parser/SimpleParserTest.java
Labels: tech-debt, integration

#587 Add github release yml file
  .github/release.yml
Labels: CI/CD

#607 Add megalinter instructions to DEVELOPING.md and move settings to separate file
  .github/linters/.mega-linter.yml
  .github/workflows/linter.yaml
  DEVELOPING.md
  README.md
Labels: CI/CD
