Repository NationalSecurityAgency/emissary, pull requests merged in 2023-09, with the labels that each got.

#545 update default socket timeout variable name
  src/main/java/emissary/client/EmissaryClient.java
  src/main/resources/emissary/client/EmissaryClient.cfg
  src/test/java/emissary/client/EmissaryClientTest.java
Labels: integration

#529 2361 - Added hadolint config and set failure threshold to 'error'.
  .github/workflows/super-linter.yaml
  contrib/docker/.hadolint.yaml
Labels: CI/CD

#537 update patch action to allow cherry-picking of commits
  .github/workflows/cherrypick.yml
  .github/workflows/create-patch-branch.yml
  RELEASING.md
Labels: CI/CD

#549 fix object metrics log configuration
  src/main/config/logback.xml
Labels: bug

#546 Removing pathWeight from all of Emissary
  src/main/java/emissary/client/response/Directory.java
  src/main/java/emissary/directory/DirectoryEntry.java
  src/main/java/emissary/directory/DirectoryPlace.java
  src/main/java/emissary/server/mvc/DumpDirectoryAction.java
  src/main/resources/templates/dump_directory.mustache
  src/test/java/emissary/directory/DirectoryEntryTest.java
  src/test/java/emissary/server/api/EmissaryApiTest.java
Labels: integration

#530 Adding objectTrace logger to output configurable fields to a new log file from PickUpPlace
  src/main/config/logback.xml
  src/main/java/emissary/pickup/PickUpPlace.java
  src/main/java/emissary/util/CustomRolloverLogbackAppender.java
  src/main/java/emissary/util/ObjectTracing.java
  src/main/resources/emissary/pickup/file/FilePickUpPlace.cfg
  src/main/resources/emissary/util/CustomRolloverLogbackAppender.cfg
Labels: feature

#552 jetty 10
  README.md
  pom.xml
  src/main/java/emissary/command/HttpCommand.java
  src/main/java/emissary/pickup/WorkSpace.java
  src/main/java/emissary/server/EmissaryServer.java
  src/test/java/emissary/server/EmissaryServerIT.java
Labels: dependencies, integration

#586 Fix ServiceConfigGuide bug.
  src/main/java/emissary/config/ServiceConfigGuide.java
  src/test/java/emissary/config/ServiceConfigGuideTest.java
Labels: bug

#585 remove unnecessary modifiers
  src/main/java/emissary/core/IBaseDataObject.java
  src/main/java/emissary/core/IMobileAgent.java
  src/main/java/emissary/kff/KffFilter.java
  src/main/java/emissary/pool/MoveSpool.java
Labels: tech-debt

#584 remove unnecessary semicolons
  src/main/java/emissary/core/DiffCheckConfiguration.java
  src/main/java/emissary/kff/ChecksumCalculator.java
  src/main/java/emissary/kff/Ssdeep.java
  src/main/java/emissary/pickup/file/FilePickUpClient.java
  src/main/java/emissary/util/LineTokenizer.java
  src/main/java/emissary/util/shell/ReadOutputLogger.java
Labels: tech-debt

#583 fix some logging statements
  src/main/java/emissary/jni/JNI.java
  src/main/java/emissary/pickup/PickUpPlace.java
Labels: bug

#582 remove explicit types and replace with '<>'
  src/main/java/emissary/command/WhatCommand.java
  src/main/java/emissary/core/HDMobileAgent.java
  src/main/java/emissary/core/MetricsManager.java
  src/main/java/emissary/kff/KffChain.java
  src/main/java/emissary/kff/KffDataObjectHandler.java
  src/main/java/emissary/kff/KffMemcached.java
  src/main/java/emissary/kff/KffResult.java
  src/main/java/emissary/output/DropOffUtil.java
  src/main/java/emissary/output/filter/AbstractFilter.java
  src/main/java/emissary/parser/DataIdentifier.java
  src/main/java/emissary/parser/SessionProducer.java
  src/main/java/emissary/parser/SimpleNioParser.java
  src/main/java/emissary/pickup/PickUpSpace.java
  src/main/java/emissary/pickup/PickupQueue.java
  src/main/java/emissary/pickup/file/FilePickUpPlace.java
  src/main/java/emissary/place/Main.java
  src/main/java/emissary/pool/MoveSpool.java
  src/main/java/emissary/util/FileComparator.java
  src/main/java/emissary/util/MagicNumberUtil.java
  src/main/java/emissary/util/ThreadDump.java
  src/main/java/emissary/util/UnixFile.java
  src/main/java/emissary/util/io/UnitTestFileUtils.java
  src/main/java/emissary/util/magic/MagicMath.java
  src/main/java/emissary/util/magic/MagicNumber.java
  src/main/java/emissary/util/magic/MagicNumberFactory.java
  src/main/java/emissary/util/search/FastBoyerMoore.java
  src/test/java/emissary/output/DropOffPlaceTest.java
  src/test/java/emissary/pickup/FTestFailedPickupClient.java
  src/test/java/emissary/pickup/FTestMultipleWorkSpaces.java
  src/test/java/emissary/pickup/FTestWorkSpaceMaxBundleSize.java
Labels: tech-debt

#579 remove commented out code
  src/main/java/emissary/kff/KffMemcached.java
  src/main/java/emissary/kff/Ssdeep.java
  src/main/java/emissary/pool/AgentPool.java
  src/main/java/emissary/server/EmissaryServer.java
  src/main/java/emissary/util/Version.java
  src/main/java/emissary/util/magic/MagicNumberFactory.java
  src/main/java/emissary/util/search/BackwardsTreeScanner.java
  src/main/java/emissary/util/web/UrlRequestProperty.java
Labels: tech-debt

#574 remove deprecated call using Long constructor
  src/test/java/emissary/server/EmissaryServerIT.java
Labels: tech-debt

#573 replace the call clazz.newInstance()
  src/main/java/emissary/client/EmissaryResponse.java
  src/main/java/emissary/command/BaseCommand.java
  src/main/java/emissary/core/Factory.java
  src/main/java/emissary/pickup/WorkSpace.java
  src/test/java/emissary/command/BaseCommandTest.java
  src/test/java/emissary/command/RunCommandIT.java
  src/test/java/emissary/command/ServerCommandIT.java
  src/test/java/emissary/test/core/UnitTest.java
  src/test/java/emissary/test/core/junit5/UnitTest.java
Labels: tech-debt

#554 Fix IBaseDataObjectXmlCodec bug.
  src/main/java/emissary/core/IBaseDataObjectDiffHelper.java
  src/main/java/emissary/core/IBaseDataObjectXmlCodecs.java
  src/main/java/emissary/core/constants/IbdoMethodNames.java
  src/test/java/emissary/core/IBaseDataObjectXmlHelperTest.java
Labels: bug

#566 remove deprecated multikeywordscanner constructor
  src/main/java/emissary/util/search/MultiKeywordScanner.java
Labels: tech-debt

#567 remove deprecated workspace methods
  src/main/java/emissary/pickup/WorkSpace.java
Labels: tech-debt

#563 remove deprecated nio parser constructors
  src/main/java/emissary/parser/FillingNIOParser.java
  src/main/java/emissary/parser/NIOSessionParser.java
Labels: tech-debt

#558 remove deprecated datautil methods
  src/main/java/emissary/util/DataUtil.java
  src/test/java/emissary/util/DataUtilTest.java
Labels: tech-debt

#564 remove deprecated filecomparator
  src/main/java/emissary/util/FileComparator.java
Labels: tech-debt

#590 remove bouncycastle dependency
  pom.xml
  src/test/java/emissary/core/channels/FillChannelFactoryTest.java
Labels: dependencies, security

#580 remove obsolete language attribute
  src/main/resources/public/index.html
  src/main/resources/templates/dump_directory.mustache
  src/main/resources/templates/environment.mustache
  src/main/resources/templates/namespace.mustache
  src/main/resources/templates/pause.mustache
  src/main/resources/templates/shutdown.mustache
  src/main/resources/templates/threaddumps.mustache
  src/main/resources/templates/unpause.mustache
Labels: tech-debt

#581 make transformhistory serializable
  src/main/java/emissary/core/TransformHistory.java
Labels: tech-debt

#575 update httpclient call to use a response handler
  src/main/java/emissary/client/EmissaryClient.java
  src/main/java/emissary/client/EmissaryResponse.java
  src/test/java/emissary/directory/HeartbeatManagerTest.java
Labels: tech-debt

#589 rename/remove sep methods
  src/main/java/emissary/core/Family.java
  src/test/java/emissary/core/FamilyTest.java
  src/test/java/emissary/util/ShortNameComparatorTest.java
Labels: integration

#569 remove deprecated datetimeformatparserlegacy
  src/main/java/emissary/util/DateTimeFormatParserLegacy.java
  src/main/resources/emissary/util/DateTimeFormatParserLegacy.cfg
Labels: tech-debt

#595 jetty 10.0.15
  pom.xml
Labels: dependencies
