Repository NationalSecurityAgency/emissary, pull requests merged in 2023-03, with the labels that each got.

#415 sanitizate FormParam strings in mvc actions
  src/main/java/emissary/server/mvc/DumpDirectoryAction.java
  src/main/java/emissary/server/mvc/TransferDirectoryAction.java
  src/main/java/emissary/server/mvc/adapters/RequestUtil.java
  src/main/java/emissary/server/mvc/internal/DeregisterPlaceAction.java
  src/main/java/emissary/server/mvc/internal/FailDirectoryAction.java
  src/main/java/emissary/server/mvc/internal/HeartbeatAction.java
  src/main/java/emissary/server/mvc/internal/RegisterPeerAction.java
  src/main/java/emissary/server/mvc/internal/WorkBundleCompletedAction.java
  src/main/java/emissary/server/mvc/internal/WorkSpaceClientOpenWorkSpaceAction.java
  src/main/java/emissary/server/mvc/internal/WorkSpaceClientSpaceTakeAction.java
  src/test/java/emissary/server/mvc/internal/DeregisterPlaceActionTest.java
  src/test/java/emissary/server/mvc/internal/FailDirectoryActionTest.java
  src/test/java/emissary/server/mvc/internal/RegisterPeerActionTest.java
  src/test/java/emissary/server/mvc/internal/WorkSpaceClientSpaceTakeActionTest.java
Labels: security

#429 Fix builds with more recent versions of Maven, incl GitHub actions
  pom.xml
Labels: bug, CI/CD

#424 sonar :: use isAssignableFrom (bug)
  src/main/java/emissary/place/ServiceProviderPlace.java
Labels: tech-debt

#423 sonar :: compare using equals() (bug)
  src/main/java/emissary/core/MobileAgent.java
Labels: tech-debt

#430 sanitize bundleId and roll outputs user defined parameters
  src/main/java/emissary/server/mvc/internal/RollOutputsAction.java
  src/main/java/emissary/server/mvc/internal/WorkBundleCompletedAction.java
Labels: security

#428 sonar :: DirectoryAdapter cleanup
  src/main/java/emissary/server/mvc/adapters/DirectoryAdapter.java
Labels: tech-debt

#438 codeql :: uncontrolled data used in path expression
  src/main/java/emissary/output/DropOffUtil.java
Labels: security

#435 sonar :: synchronize on private final field in MonitorCommand (bug)
  src/main/java/emissary/command/MonitorCommand.java
Labels: tech-debt

#432 sonar :: check the return value of InputStream#read(byte[]) (bug)
  src/main/java/emissary/kff/KffChainLoader.java
  src/main/java/emissary/kff/KffFile.java
  src/main/java/emissary/kff/KffQuincyFile.java
  src/main/java/emissary/kff/Ssdeep.java
  src/main/java/emissary/util/Hexl.java
  src/main/java/emissary/util/Version.java
  src/test/java/emissary/kff/KffDataObjectHandlerTest.java
  src/test/java/emissary/test/core/ExtractionTest.java
  src/test/java/emissary/test/core/IdentificationTest.java
  src/test/java/emissary/test/core/junit5/ExtractionTest.java
  src/test/java/emissary/test/core/junit5/IdentificationTest.java
Labels: tech-debt

#434 sonar :: KffFile cleanup
  src/main/java/emissary/kff/KffFile.java
Labels: tech-debt

#440 executrix remove ulimit vmem for mac os
  src/main/java/emissary/util/shell/Executrix.java
Labels: bug

#437 sonar :: return values should not be ignored in DropOffUtil (bug)
  src/main/java/emissary/output/DropOffUtil.java
Labels: tech-debt

#427 sonar :: fix conditionally executed code should be reachable (bug)
  src/main/java/emissary/command/WhatCommand.java
  src/main/java/emissary/place/sample/TemplatePlace.java
  src/main/java/emissary/util/FlexibleDateTimeParser.java
  src/main/java/emissary/util/StringUtil.java
Labels: tech-debt

#446 Identify duplicate classes on classpath
  DEVELOPING.md
  pom.xml
Labels: feature

#445 Verify class locations during initialization
  src/main/config/emissary.spi.ClassLocationVerificationProvider.cfg
  src/main/java/emissary/spi/ClassLocationVerificationProvider.java
  src/main/resources/META-INF/services/emissary.spi.InitializationProvider
  src/test/java/emissary/spi/ClassLocationVerificationProviderTest.java
Labels: feature
