Repository NationalSecurityAgency/emissary, pull requests merged in 2023-08, with the labels that each got.

#515 RegressionTest updates.
  src/main/java/emissary/core/IBaseDataObjectXmlCodecs.java
  src/main/java/emissary/core/IBaseDataObjectXmlHelper.java
  src/main/java/emissary/util/ByteUtil.java
  src/test/java/emissary/core/IBaseDataObjectHelperTest.java
  src/test/java/emissary/core/IBaseDataObjectXmlHelperTest.java
  src/test/java/emissary/test/core/junit5/RegressionTest.java
  src/test/java/emissary/test/core/junit5/RegressionTestUtil.java
Labels: enhancement

#526 add RELEASING.md document
  RELEASING.md
Labels: documentation

#514 Replace JCommander with Picocli
  DEVELOPING.md
  README.md
  emissary
  pom.xml
  src/main/java/emissary/Emissary.java
  src/main/java/emissary/command/AgentsCommand.java
  src/main/java/emissary/command/BaseCommand.java
  src/main/java/emissary/command/ConfigCommand.java
  src/main/java/emissary/command/DirectoryCommand.java
  src/main/java/emissary/command/EmissaryCommand.java
  src/main/java/emissary/command/EnvCommand.java
  src/main/java/emissary/command/FeedCommand.java
  src/main/java/emissary/command/HelpCommand.java
  src/main/java/emissary/command/HttpCommand.java
  src/main/java/emissary/command/MonitorCommand.java
  src/main/java/emissary/command/PeersCommand.java
  src/main/java/emissary/command/PoolCommand.java
  src/main/java/emissary/command/RunCommand.java
  src/main/java/emissary/command/ServerCommand.java
  src/main/java/emissary/command/ServiceCommand.java
  src/main/java/emissary/command/StopCommand.java
  src/main/java/emissary/command/TopologyCommand.java
  src/main/java/emissary/command/VersionCommand.java
  src/main/java/emissary/command/WhatCommand.java
  src/main/java/emissary/command/converter/FileExistsConverter.java
  src/main/java/emissary/command/converter/PathExistsConverter.java
  src/main/java/emissary/command/converter/PathExistsReadableConverter.java
  src/main/java/emissary/command/converter/PriorityDirectoryConverter.java
  src/main/java/emissary/command/converter/ProjectBaseConverter.java
  src/main/java/emissary/command/converter/WhatCommandPathExistsConverter.java
  src/main/java/emissary/command/converter/WorkspaceSortModeConverter.java
  src/main/java/emissary/command/package-info.java
  src/main/java/emissary/command/validator/ServerModeValidator.java
  src/test/java/emissary/EmissaryTest.java
  src/test/java/emissary/command/BaseCommandTest.java
  src/test/java/emissary/command/FeedCommandIT.java
  src/test/java/emissary/command/PeersCommandIT.java
  src/test/java/emissary/command/RunCommandIT.java
  src/test/java/emissary/command/WhatCommandIT.java
  src/test/java/emissary/command/converter/PriorityDirectoryConverterTest.java
Labels: enhancement, integration, major

#536 update release action to check suffix is not specified for a release or patch
  .github/workflows/maven-release.yml
Labels: CI/CD

#255 remove windows support
  src/main/config/emissary.output.DropOffPlace.cfg
  src/main/java/emissary/config/ConfigUtil.java
  src/main/java/emissary/core/BaseDataObject.java
  src/main/java/emissary/output/DropOffUtil.java
  src/main/java/emissary/pickup/PickUpPlace.java
  src/main/java/emissary/pickup/file/FilePickUpClient.java
  src/main/java/emissary/util/shell/Executrix.java
  src/main/resources/emissary/jni/JNI.cfg
  src/main/resources/emissary/output/DropOffPlace.cfg
  src/main/resources/emissary/pickup/file/FilePickUpClient.cfg
  src/main/resources/emissary/pickup/file/FilePickUpPlace.cfg
  src/test/java/emissary/config/ConfigUtilTest.java
  src/test/java/emissary/core/BaseDataObjectTest.java
  src/test/java/emissary/util/shell/ExecutrixTest.java
  src/test/resources/emissary/pickup/BreakableFilePickUpClient.cfg
  src/test/resources/emissary/pickup/FilePickUpClient.cfg
  src/test/resources/emissary/pickup/file/FTestSpacePlaceInteraction.cfg
Labels: major

#543 Removing * import from UnixFilePlace
  src/main/java/emissary/id/UnixFilePlace.java
Labels: tech-debt

#505 Add ability to deny service proxy values for places
  src/main/java/emissary/core/HDMobileAgent.java
  src/main/java/emissary/core/MobileAgent.java
  src/main/java/emissary/core/constants/Configurations.java
  src/main/java/emissary/directory/DirectoryPlace.java
  src/main/java/emissary/place/IServiceProviderPlace.java
  src/main/java/emissary/place/ServiceProviderPlace.java
  src/main/resources/emissary/place/sample/DelayPlace.cfg
  src/test/java/emissary/core/MobileAgentTest.java
  src/test/java/emissary/directory/RoutingAlgorithmTest.java
  src/test/java/emissary/place/ServiceProviderPlaceTest.java
Labels: feature

#532 Migrate HttpClient from 4.x to 5.x
  pom.xml
  src/main/java/emissary/client/EmissaryClient.java
  src/main/java/emissary/client/EmissaryResponse.java
  src/main/java/emissary/client/HTTPConnectionFactory.java
  src/main/java/emissary/command/AgentsCommand.java
  src/main/java/emissary/command/ConfigCommand.java
  src/main/java/emissary/command/DirectoryCommand.java
  src/main/java/emissary/command/EnvCommand.java
  src/main/java/emissary/command/HttpCommand.java
  src/main/java/emissary/command/PoolCommand.java
  src/main/java/emissary/command/TopologyCommand.java
  src/main/java/emissary/directory/HeartbeatManager.java
  src/main/java/emissary/pickup/WorkSpace.java
  src/main/java/emissary/server/EmissaryServer.java
  src/main/java/emissary/server/api/Agents.java
  src/main/java/emissary/server/api/Peers.java
  src/main/java/emissary/server/api/Places.java
  src/main/java/emissary/server/api/Pool.java
  src/main/java/emissary/server/api/Version.java
  src/main/java/emissary/server/mvc/adapters/DirectoryAdapter.java
  src/main/java/emissary/server/mvc/adapters/WorkSpaceAdapter.java
  src/test/java/emissary/client/EmissaryClientTest.java
  src/test/java/emissary/core/FTestMovingAgent.java
  src/test/java/emissary/directory/HeartbeatManagerTest.java
  src/test/java/emissary/server/EmissaryServerIT.java
Labels: dependencies, integration

#268 sonarlint :: command.converter package
  src/main/java/emissary/command/converter/PathExistsConverter.java
  src/main/java/emissary/command/converter/PriorityDirectoryConverter.java
  src/main/java/emissary/command/converter/ProjectBaseConverter.java
  src/test/java/emissary/command/converter/FileExistsConverterTest.java
  src/test/java/emissary/command/converter/PathExistsConverterTest.java
  src/test/java/emissary/command/converter/ProjectBaseConverterTest.java
Labels: tech-debt

#224 UI :: updates the navbar code for the ui
  src/main/java/emissary/server/api/Nav.java
  src/main/java/emissary/server/mvc/NavAction.java
  src/main/resources/emissary/server/mvc/NavAction.cfg
  src/main/resources/public/index.html
  src/main/resources/public/js/emissary.js
  src/main/resources/public/js/emissary_nav.js
  src/main/resources/templates/dump_directory.mustache
  src/main/resources/templates/environment.mustache
  src/main/resources/templates/namespace.mustache
  src/main/resources/templates/nav.mustache
  src/main/resources/templates/pause.mustache
  src/main/resources/templates/shutdown.mustache
  src/main/resources/templates/threaddumps.mustache
  src/main/resources/templates/unpause.mustache
Labels: integration, major

#547 update impsort plugin to 1.8.0
  pom.xml
Labels: dependencies
