Repository NationalSecurityAgency/emissary, pull requests merged in 2024-04, with the labels that each got.

#737 unit-tests :: move HDMobileAgentBugTest to HDMobileAgentBugIT
  src/test/java/emissary/core/HDMobileAgentBugIT.java
Labels: test-only

#736 unit-tests :: remove WhyDoYouMakeMeDoThisExtractionTest
  src/test/java/emissary/test/core/junit5/TestExtractionTest.java
Labels: test-only

#729 errorprone :: add an errorprone CI build action
  .github/workflows/maven-ci.yml
Labels: CI/CD

#690 change to use ClassNameInventory file naming convention
  src/main/config/emissary.admin.ClassNameInventory.cfg
  src/main/java/emissary/admin/PlaceStarter.java
  src/main/java/emissary/config/ConfigUtil.java
  src/test/java/emissary/config/ConfigUtilTest.java
Labels: integration

#734 errorprone :: MissingBraces and UnnecessaryParentheses
  src/main/java/emissary/command/BaseCommand.java
  src/main/java/emissary/config/ServiceConfigGuide.java
  src/main/java/emissary/core/MobileAgent.java
  src/main/java/emissary/directory/EmissaryNode.java
  src/main/java/emissary/jni/JNI.java
  src/main/java/emissary/jni/JniRepositoryPlace.java
  src/main/java/emissary/kff/EditDistance.java
  src/main/java/emissary/kff/SpamSumSignature.java
  src/main/java/emissary/output/roller/journal/JournalReader.java
  src/main/java/emissary/output/roller/journal/JournaledChannel.java
  src/main/java/emissary/pickup/file/FileDataServer.java
  src/main/java/emissary/place/MultiFileUnixCommandPlace.java
  src/main/java/emissary/place/ServiceProviderPlace.java
  src/main/java/emissary/place/UnixCommandPlace.java
  src/main/java/emissary/server/EmissaryServer.java
  src/main/java/emissary/server/mvc/adapters/DirectoryAdapter.java
  src/main/java/emissary/transform/HtmlEscapePlace.java
  src/main/java/emissary/transform/decode/HtmlEscape.java
  src/main/java/emissary/transform/decode/JsonEscape.java
  src/main/java/emissary/util/CharacterCounterSet.java
  src/main/java/emissary/util/CounterSet.java
  src/main/java/emissary/util/DependencyCheck.java
  src/main/java/emissary/util/Hexl.java
  src/main/java/emissary/util/io/BufferedWriterOutputStream.java
  src/main/java/emissary/util/io/FileManipulator.java
  src/main/java/emissary/util/magic/MagicMath.java
  src/main/java/emissary/util/magic/MagicNumber.java
  src/main/java/emissary/util/search/ByteMatcher.java
  src/main/java/emissary/util/shell/Executrix.java
  src/test/java/emissary/config/ServiceConfigGuideTest.java
  src/test/java/emissary/test/core/junit5/IdentificationTest.java
  src/test/java/emissary/util/PayloadUtilTest.java
Labels: tech-debt

#672 update groupId to gov.nsa.emissary
  pom.xml
Labels: integration, major

#694 switch to using main branch in actions
  .github/workflows/cherrypick.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/linter.yaml
  .github/workflows/maven-ci.yml
  .github/workflows/maven-release.yml
  .github/workflows/maven-version.yml
  RELEASING.md
Labels: CI/CD

#728 errorprone :: tackle a handful of single occurrence rules
  src/main/java/emissary/command/FeedCommand.java
  src/main/java/emissary/command/HttpCommand.java
  src/main/java/emissary/core/DataObjectFactory.java
  src/main/java/emissary/kff/SpamSumSignature.java
  src/main/java/emissary/output/DropOffUtil.java
  src/main/java/emissary/output/roller/JournaledCoalescer.java
  src/main/java/emissary/util/FlexibleDateTimeParser.java
  src/test/java/emissary/core/ResourceWatcherTest.java
  src/test/java/emissary/core/channels/ChannelTestHelper.java
  src/test/java/emissary/output/filter/DataFilterTest.java
  src/test/java/emissary/parser/MyDataIdentifierTest.java
  src/test/java/emissary/place/CoordinationPlaceTest.java
  src/test/java/emissary/util/EmissaryIsolatedClassLoaderExtension.java
  src/test/java/emissary/util/PayloadUtilTest.java
  src/test/java/emissary/util/io/LoggingPrintStreamTest.java
Labels: tech-debt

#740 remove unreachable code block in CharacterCounterSet
  src/main/java/emissary/util/CharacterCounterSet.java
Labels: tech-debt

#741 documentation changes for groupId update
  README.md
  RELEASING.md
Labels: documentation

#735 errorprone :: UnnecessarilyFullyQualified
  src/main/java/emissary/Emissary.java
  src/main/java/emissary/core/IMobileAgent.java
  src/main/java/emissary/core/NamespaceException.java
  src/main/java/emissary/id/UnixFilePlace.java
  src/main/java/emissary/jni/JNI.java
  src/main/java/emissary/output/DropOffUtil.java
  src/main/java/emissary/output/filter/AbstractFilter.java
  src/main/java/emissary/pickup/IPickUpSpace.java
  src/main/java/emissary/pickup/PickUpPlace.java
  src/main/java/emissary/pickup/PickUpSpace.java
  src/main/java/emissary/pickup/WorkSpace.java
  src/main/java/emissary/place/IMultiFileServerPlace.java
  src/main/java/emissary/place/IMultiFileUnixCommandPlace.java
  src/main/java/emissary/place/ServiceProviderPlace.java
  src/main/java/emissary/pool/AgentThreadGroup.java
  src/main/java/emissary/util/DateTimeFormatParser.java
  src/main/java/emissary/util/DateTimeFormatParserLegacy.java
  src/test/java/emissary/command/PeersCommandIT.java
  src/test/java/emissary/config/ConfigUtilTest.java
  src/test/java/emissary/core/BaseDataObjectTest.java
  src/test/java/emissary/core/FTestMobileAgent.java
  src/test/java/emissary/core/FTestMovingAgent.java
  src/test/java/emissary/core/FactoryTest.java
  src/test/java/emissary/core/IExtendedDataObject.java
  src/test/java/emissary/core/ResourceWatcherTest.java
  src/test/java/emissary/util/CaseInsensitiveMapTest.java
Labels: tech-debt

#746 Skip slack notifications if running on a fork
  .github/workflows/maven-ci.yml
  .github/workflows/maven-release.yml
Labels: CI/CD

#749 sonarlint :: deprecate finalize method in JournaledCoalescer
  src/main/java/emissary/output/roller/JournaledCoalescer.java
Labels: tech-debt

#730 errorprone :: single instance warnings in some helper and test classes
  src/main/java/emissary/core/IBaseDataObjectXmlCodecs.java
  src/main/java/emissary/core/SafeUsageChecker.java
  src/main/java/emissary/core/channels/SeekableByteChannelHelper.java
  src/main/java/emissary/util/ByteUtil.java
  src/main/java/emissary/util/PlaceComparisonHelper.java
  src/test/java/emissary/core/BaseDataObjectTest.java
  src/test/java/emissary/core/channels/SeekableByteChannelHelperTest.java
  src/test/java/emissary/util/PlaceComparisonHelperTest.java
Labels: tech-debt

#744 upgrade dropwizard metrics to 4.2.25
  pom.xml
Labels: dependencies, security

#751 add ubi8 build to ci
  .github/workflows/maven-ci.yml
  contrib/docker/Dockerfile.ubi8
Labels: CI/CD

#753 Check repo name for slack notification
  .github/workflows/maven-ci.yml
  .github/workflows/maven-release.yml
Labels: CI/CD

#754 update action name syntax for release
  .github/workflows/maven-release.yml
Labels: CI/CD

#758 fix typo in create-patch-branch message
  .github/workflows/create-patch-branch.yml
Labels: CI/CD

#760 Pull out LoggingInputStream for use with any InputStream.
  src/main/java/emissary/core/channels/LoggingInputStreamFactory.java
  src/main/java/emissary/util/io/LoggingInputStream.java
Labels: enhancement

#766 github-actions :: block slack links from being unfurled in messages
  .github/workflows/maven-ci.yml
  .github/workflows/maven-release.yml
Labels: CI/CD

#765 docker ci build
  .dockerignore
  .github/workflows/maven-ci.yml
  contrib/docker/Dockerfile.ci
  contrib/docker/Dockerfile.ubi8
  contrib/docker/docker-compose.ubi8.yml
Labels: CI/CD
