Repository NationalSecurityAgency/emissary, pull requests merged in 2024-09, with the labels that each got.

#899 No longer preserving MD5_ORIGINAL if re-hashing hasn't changed the value
  src/main/java/emissary/kff/KffDataObjectHandler.java
Labels: priority

#906 remove duplicate JsonEscapePlace inventory entry
  src/main/config/emissary.admin.ClassNameInventory.cfg
Labels: tech-debt

#904 errorprone: FieldCanBeStatic - JsonOutputFilter
  src/main/java/emissary/output/filter/JsonOutputFilter.java
Labels: tech-debt

#908 errorprone: LongDoubleConversion - suppress in MetricsFormatter
  src/main/java/emissary/core/MetricsFormatter.java
Labels: tech-debt

#910 errorprone: MissingOverride - ByteTokenizer
  src/main/java/emissary/util/search/ByteTokenizer.java
Labels: tech-debt

#909 errorprone: DifferentNameButSame
  src/main/java/emissary/kff/KffChainLoader.java
  src/main/java/emissary/server/EmissaryServer.java
Labels: tech-debt

#912 errorprone: StaticQualifiedUsingExpression
  src/main/java/emissary/pickup/WorkSpace.java
Labels: tech-debt

#905 errorprone: ImmutableMemberCollection - suppressing in Emissary class
  src/main/java/emissary/Emissary.java
Labels: tech-debt

#916 errorprone :: AvoidObjectArrays in Url and UrlData
  src/main/java/emissary/util/web/Url.java
  src/main/java/emissary/util/web/UrlData.java
  src/test/java/emissary/util/web/UrlDataTest.java
Labels: tech-debt

#918 errorprone :: UnitTest - MethodCanBeStatic, InconsistentOverloads, No…
  src/test/java/emissary/test/core/junit5/UnitTest.java
Labels: tech-debt, test-only

#913 errorprone :: move ThreadDump to test package and removed unused methods
  src/main/java/emissary/util/ThreadDump.java
  src/test/java/emissary/test/core/junit5/UnitTest.java
  src/test/java/emissary/test/util/ThreadDump.java
Labels: integration

#926 Fixing missed negation in KffDataObjectHandler.previouslyComputedMd5HasChanged
  src/main/java/emissary/kff/KffDataObjectHandler.java
  src/test/java/emissary/kff/KffDataObjectHandlerTest.java
Labels: bug

#924 errorprone :: VersionPlaceTest FieldMissingNullable
  src/test/java/emissary/place/VersionPlaceTest.java
Labels: tech-debt, test-only

#923 update 'dep.' names and use 'plugin.' prefix for plugins in pom
  pom.xml
Labels: tech-debt

#927 update formatter to use 11 compliance
  contrib/formatter.xml
Labels: tech-debt

#929 errorprone :: fix sysout ServiceProviderPlaceGetTLDTest
  src/test/java/emissary/place/ServiceProviderPlaceGetTLDTest.java
Labels: tech-debt

#928 errorprone :: ignore sysout PeersCommandIT
  src/test/java/emissary/command/PeersCommandIT.java
Labels: tech-debt

#823 ci :: updating docker compose to allow for testing
  .github/workflows/maven-ci.yml
  contrib/docker/Dockerfile.ci
  contrib/docker/docker-compose.ci.yml
Labels: CI/CD

#925 Made AbstractFilter Denylist settings configurable
  src/main/java/emissary/output/filter/AbstractFilter.java
  src/test/java/emissary/output/filter/AbstractFilterTest.java
Labels: enhancement

#934 errorprone :: ignore FTest warnings
  src/test/java/emissary/pickup/FTestMultipleWorkSpaces.java
  src/test/java/emissary/pickup/FTestWorkSpaceMaxBundleSize.java
  src/test/java/emissary/pickup/file/FTestSpacePlaceInteraction.java
Labels: test-only

#940 errorprone :: CheckedExceptionNotThrown in JournaledCoalescer
  src/main/java/emissary/output/roller/JournaledCoalescer.java
Labels: tech-debt

#946 errorprone/sonar :: MagicNumber
  src/main/java/emissary/util/magic/MagicNumber.java
Labels: tech-debt

#943 errorprone :: SystemOut in JniRepositoryPlace
  src/main/java/emissary/jni/JniRepositoryPlace.java
Labels: tech-debt

#939 errorprone :: CheckedExceptionNotThrown in FillChannelFactory
  src/main/java/emissary/core/channels/FillChannelFactory.java
Labels: tech-debt

#944 errorprone :: FutureReturnValueIgnored
  src/main/java/emissary/core/sentinel/protocols/actions/Kill.java
  src/main/java/emissary/core/sentinel/protocols/actions/Stop.java
  src/main/java/emissary/kff/KffMemcached.java
  src/main/java/emissary/roll/RollManager.java
  src/main/java/emissary/util/io/LoggingPrintStream.java
Labels: tech-debt

#936 errorprone :: CheckedExceptionNotThrown in JournalReader
  src/main/java/emissary/output/roller/journal/JournalReader.java
Labels: tech-debt

#937 errorprone :: CheckedExceptionNotThrown in ImmutableChannelFactory
  src/main/java/emissary/core/channels/ImmutableChannelFactory.java
Labels: tech-debt

#947 exclude github-actions[bot] changes from release notes
  .github/release.yml
Labels: CI/CD

#951 change release note categories
  .github/release.yml
Labels: CI/CD

#953 add icons to release notes
  .github/release.yml
Labels: CI/CD

#955 fix github-actions author exclusion
  .github/release.yml
Labels: CI/CD

#188 Improved ExtractionTest Validation of Attachment and Extracted Children Expected vs Found Count
  src/test/java/emissary/test/core/junit5/ExtractionTest.java
Labels: enhancement, integration

#931 errorprone :: FlexibleDateTimeParser
  src/main/java/emissary/util/FlexibleDateTimeParser.java
  src/test/java/emissary/util/FlexibleDateTimeParserTest.java
Labels: tech-debt

#932 errorprone :: StringCaseLocaleUsage
  src/main/java/emissary/admin/Startup.java
  src/main/java/emissary/command/FeedCommand.java
  src/main/java/emissary/command/HttpCommand.java
  src/main/java/emissary/command/ServerCommand.java
  src/main/java/emissary/config/ConfigUtil.java
  src/main/java/emissary/config/ServiceConfigGuide.java
  src/main/java/emissary/directory/EmissaryNode.java
  src/main/java/emissary/id/UnixFilePlace.java
  src/main/java/emissary/output/DropOffUtil.java
  src/main/java/emissary/output/filter/AbstractFilter.java
  src/main/java/emissary/output/filter/AbstractRollableFilter.java
  src/main/java/emissary/output/filter/JsonOutputFilter.java
  src/main/java/emissary/util/CaseInsensitiveMap.java
  src/main/java/emissary/util/JavaCharSet.java
  src/main/java/emissary/util/TypeEngine.java
  src/main/java/emissary/util/magic/MagicNumberFactory.java
Labels: tech-debt

#935 errorprone :: NonFinalStaticFields in SizeUtil
  src/main/java/emissary/util/SizeUtil.java
Labels: tech-debt

#938 errorprone :: ThrowsUncheckedException
  src/main/java/emissary/config/Configurator.java
  src/main/java/emissary/config/ServiceConfigGuide.java
  src/main/java/emissary/server/mvc/internal/WorkBundleCompletedAction.java
  src/main/java/emissary/server/mvc/internal/WorkSpaceClientOpenWorkSpaceAction.java
  src/main/java/emissary/util/TimeUtil.java
Labels: tech-debt

#948 errorprone: InconsistentOverloads - deprecate and ignore
  src/main/java/emissary/directory/HeartbeatManager.java
  src/main/java/emissary/roll/Roller.java
  src/main/java/emissary/util/ByteUtil.java
  src/main/java/emissary/util/io/FastStringBuffer.java
  src/main/java/emissary/util/xml/AbstractJDOMUtil.java
Labels: tech-debt

#945 errorprone :: LoopOverCharArray
  src/test/java/emissary/output/filter/AbstractFilterTest.java
Labels: tech-debt, test-only

#941 dependencies: upgrade janino dependency to 3.1.12
  pom.xml
Labels: dependencies, security

#956 Bump plugin.versions-maven.version from 2.14.2 to 2.17.1
  pom.xml
Labels: dependencies, BPD

#958 errorprone :: InconsistentOverloads
  src/main/java/emissary/output/roller/JournaledCoalescer.java
  src/main/java/emissary/parser/ParserFactory.java
  src/main/java/emissary/place/MultiFileUnixCommandPlace.java
  src/main/java/emissary/util/shell/Executrix.java
  src/test/java/emissary/util/shell/ExecutrixTest.java
Labels: tech-debt

#957 run maven sortpom before committing release version bump
  .github/workflows/maven-release.yml
Labels: CI/CD
