Repository NationalSecurityAgency/emissary, pull requests merged in 2024-07, with the labels that each got.

#838 updated centos 7 to pull from vault
  contrib/docker/Dockerfile.ci
Labels: CI/CD

#840 errorprone :: MethodCanBeStatic
  src/main/java/emissary/admin/Startup.java
  src/main/java/emissary/client/EmissaryResponse.java
  src/main/java/emissary/config/ExtractResource.java
  src/main/java/emissary/kff/KffChain.java
  src/main/java/emissary/kff/KffFile.java
  src/main/java/emissary/server/EmissaryServer.java
  src/main/java/emissary/server/mvc/PauseAction.java
  src/main/java/emissary/server/mvc/adapters/DirectoryAdapter.java
  src/main/java/emissary/server/mvc/internal/HeartbeatAction.java
  src/main/java/emissary/server/mvc/internal/WorkBundleCompletedAction.java
  src/main/java/emissary/server/mvc/internal/WorkSpaceClientSpaceTakeAction.java
  src/main/java/emissary/util/WindowedSeekableByteChannel.java
  src/main/java/emissary/util/search/KeywordScanner.java
  src/main/java/emissary/util/shell/Executrix.java
  src/test/java/emissary/util/FlexibleDateTimeParserTest.java
Labels: tech-debt

#841 errorprone :: UnusedException
  src/main/java/emissary/core/sentinel/protocols/actions/Recover.java
  src/main/java/emissary/util/magic/MagicNumberFactory.java
  src/main/java/emissary/util/search/ByteTokenizer.java
Labels: tech-debt

#839 Update startup logging
  src/main/config/logback.xml
  src/main/java/emissary/admin/Startup.java
Labels: tech-debt

#845 errorprone :: MemberName - ByteUtil
  src/main/java/emissary/util/ByteUtil.java
  src/test/java/emissary/util/DataUtilTest.java
Labels: tech-debt

#855 errorprone :: MemberName - FastStringBuffer
  src/main/java/emissary/util/io/FastStringBuffer.java
Labels: tech-debt

#854 errorprone :: MemberName - pickup package
  src/main/java/emissary/pickup/PickUpPlace.java
  src/main/java/emissary/pickup/WorkBundle.java
  src/main/java/emissary/pickup/WorkUnit.java
  src/main/java/emissary/spi/ObjectTracing.java
  src/test/java/emissary/pickup/WorkBundleTest.java
Labels: tech-debt

#851 errorprone :: MemberName - StringUtil
  src/main/java/emissary/util/StringUtil.java
Labels: tech-debt

#850 errorprone :: MemberName - JDOMUtil
  src/main/java/emissary/util/xml/AbstractJDOMUtil.java
  src/main/java/emissary/util/xml/SaferJDOMUtil.java
  src/test/java/emissary/util/xml/JDOMUtilTest.java
Labels: tech-debt

#853 errorprone :: MemberName - directory package
  src/main/java/emissary/directory/DirectoryEntryList.java
  src/main/java/emissary/directory/DirectoryXmlContainer.java
  src/main/java/emissary/directory/WildcardEntry.java
  src/test/java/emissary/directory/DirectoryEntryListTest.java
Labels: tech-debt

#848 errorprone :: MemberName - SizeUtil
  src/main/java/emissary/util/SizeUtil.java
Labels: tech-debt

#860 errorprone :: suppress HidingField
  src/test/java/emissary/core/channels/LoggingChannelFactoryTest.java
  src/test/java/emissary/core/channels/LoggingInputStreamFactoryTest.java
  src/test/java/emissary/test/core/junit5/LogbackTesterTest.java
  src/test/java/emissary/util/DisposeHelperTest.java
Labels: tech-debt, test-only

#859 errorprone :: suppress system out in main method
  src/main/java/emissary/admin/Startup.java
  src/main/java/emissary/command/Banner.java
  src/main/java/emissary/config/ExtractResource.java
  src/main/java/emissary/jni/JniRepositoryPlace.java
  src/main/java/emissary/kff/KffChainLoader.java
  src/main/java/emissary/kff/KffQuincyFile.java
  src/main/java/emissary/kff/SpamSumSignature.java
  src/main/java/emissary/kff/Ssdeep.java
  src/main/java/emissary/output/filter/DataFilter.java
  src/main/java/emissary/output/filter/XmlOutputFilter.java
  src/main/java/emissary/output/roller/journal/JournalReader.java
  src/main/java/emissary/parser/DataIdentifier.java
  src/main/java/emissary/transform/decode/HtmlEscape.java
  src/main/java/emissary/transform/decode/JavascriptEscape.java
  src/main/java/emissary/transform/decode/JsonEscape.java
  src/main/java/emissary/util/ClassComparator.java
  src/main/java/emissary/util/Hexl.java
  src/main/java/emissary/util/HtmlEntityMap.java
  src/main/java/emissary/util/UnixFile.java
  src/main/java/emissary/util/WatcherThread.java
  src/main/java/emissary/util/io/FileFind.java
Labels: tech-debt

#847 errorprone :: MemberName - TimeUtil
  src/main/java/emissary/util/TimeUtil.java
Labels: tech-debt

#862 add TransformHistory test class
  src/test/java/emissary/core/TransformHistoryTest.java
Labels: test-only

#858 removing public modifiers from junit5 tests where applicable
  src/test/java/emissary/core/SafeUsageCheckerTest.java
  src/test/java/emissary/core/TransformHistoryTest.java
  src/test/java/emissary/parser/InputSessionTest.java
  src/test/java/emissary/pool/AgentPoolTest.java
  src/test/java/emissary/test/core/junit5/LogbackTesterTest.java
  src/test/java/emissary/transform/JavascriptEscapePlaceTest.java
  src/test/java/emissary/transform/JsonEscapePlaceTest.java
  src/test/java/emissary/util/DateTimeFormatParserTest.java
  src/test/java/emissary/util/PayloadUtilTest.java
Labels: tech-debt, test-only
