Repository NationalSecurityAgency/emissary, pull requests merged in 2024-12, with the labels that each got.

#1006 Update RegressionTest to assume UTF-8.
  src/main/java/emissary/core/IBaseDataObjectXmlCodecs.java
  src/test/java/emissary/core/IBaseDataObjectXmlHelperTest.java
  src/test/java/emissary/test/core/junit5/RegressionTest.java
Labels: improvement

#1013 dependencies: update commons-compress to 1.27.1 and commons-io to 2.17.0
  pom.xml
Labels: dependencies

#1017 Removed SafeUsageChecker from BaseDataObject, deprecated IBDO.checkForUnsafeDataChanges
  src/main/java/emissary/core/BaseDataObject.java
  src/main/java/emissary/core/IBaseDataObject.java
  src/main/java/emissary/place/ServiceProviderPlace.java
  src/test/java/emissary/core/BaseDataObjectTest.java
Labels: tech-debt

#1018 Deprecate IBaseDataObjectHelper.clone() that allows partial clones.
  src/main/java/emissary/core/IBaseDataObjectHelper.java
  src/test/java/emissary/core/IBaseDataObjectHelperTest.java
Labels: tech-debt

#1019 upgrade megalinter action to v8
  .github/linters/.mega-linter.yml
  .github/workflows/linter.yaml
Labels: CI/CD

#1022 change mega-linter settings to stop trying to post pr comments
  .github/linters/.mega-linter.yml
Labels: CI/CD

#1023 pre-compile regex in PriorityDirectoryConverter
  src/main/java/emissary/command/converter/PriorityDirectoryConverter.java
Labels: tech-debt

#1011 update plugins for maven 3.6.3+
  README.md
  pom.xml
Labels: dependencies, BPD

#1025 fix pmd sourceEncoding parameter warning
  pom.xml
Labels: BPD

#1028 add jacoco pmd and cpd reports to published reports
  .github/workflows/maven-ci.yml
  .github/workflows/maven-release.yml
Labels: CI/CD, BPD

#1027 Improve performance of ShortNameComparator.
  src/main/java/emissary/util/ShortNameComparator.java
  src/test/java/emissary/util/ShortNameComparatorTest.java
Labels: enhancement

#1014 ibdo :: get parameter as string
  src/main/java/emissary/core/BaseDataObject.java
  src/main/java/emissary/core/IBaseDataObject.java
  src/test/java/emissary/core/BaseDataObjectTest.java
Labels: framework, improvement

#1032 add Nullable to new getParameterAsConcatString method
  src/main/java/emissary/core/IBaseDataObject.java
Labels: tech-debt

#1026 unnecessary modifier :: variables declared in try-with-resources are …
  src/main/java/emissary/config/ExtractResource.java
  src/main/java/emissary/core/BaseDataObject.java
  src/main/java/emissary/core/channels/InputStreamChannelFactory.java
  src/main/java/emissary/core/channels/SeekableByteChannelHelper.java
  src/main/java/emissary/jni/JNI.java
  src/main/java/emissary/jni/JniRepositoryPlace.java
  src/main/java/emissary/kff/ChecksumCalculator.java
  src/main/java/emissary/kff/KffChain.java
  src/main/java/emissary/kff/KffDataObjectHandler.java
  src/main/java/emissary/kff/Ssdeep.java
  src/main/java/emissary/server/EmissaryServer.java
  src/main/java/emissary/util/PkiUtil.java
  src/main/java/emissary/util/shell/Executrix.java
  src/main/java/emissary/util/xml/AbstractJDOMUtil.java
  src/test/java/emissary/config/ServiceConfigGuideTest.java
  src/test/java/emissary/core/BaseDataObjectTest.java
  src/test/java/emissary/core/channels/ChannelTestHelper.java
  src/test/java/emissary/core/channels/ImmutableChannelFactoryTest.java
  src/test/java/emissary/core/channels/InputStreamChannelFactoryTest.java
  src/test/java/emissary/output/roller/journal/JournaledChannelPoolTest.java
  src/test/java/emissary/server/mvc/internal/DeregisterPlaceActionTest.java
  src/test/java/emissary/server/mvc/internal/FailDirectoryActionTest.java
  src/test/java/emissary/server/mvc/internal/HeartbeatActionTest.java
  src/test/java/emissary/server/mvc/internal/WorkBundleCompletedActionTest.java
Labels: tech-debt

#1034 bug :: preserve original behavior for getStringParameter
  src/main/java/emissary/core/BaseDataObject.java
  src/main/java/emissary/core/IBaseDataObject.java
  src/test/java/emissary/core/BaseDataObjectTest.java
  src/test/java/emissary/kff/KffDataObjectHandlerTest.java
  src/test/java/emissary/output/DropOffUtilTest.java
  src/test/java/emissary/place/MultiFileUnixCommandPlaceTest.java
Labels: bug
