Repository NationalSecurityAgency/emissary, pull requests merged in 2024-01, with the labels that each got.

#614 Adding search ability in directory action in API
  src/main/resources/public/js/emissary.js
  src/main/resources/templates/dump_directory.mustache
Labels: enhancement, feature

#640 fix Class raw type warning in Factory.java
  src/main/java/emissary/core/Factory.java
Labels: tech-debt

#641 address warning for unused TimedResource in t-w-r declarations
  src/main/java/emissary/core/HDMobileAgent.java
  src/main/java/emissary/core/MobileAgent.java
  src/main/java/emissary/place/CoordinationPlace.java
Labels: tech-debt

#639 update deprecated logback CONFIG_FILE_PROPERTY constant
  src/main/java/emissary/command/BaseCommand.java
Labels: tech-debt

#613 Removing date parsing bug workaround
  src/main/java/emissary/util/FlexibleDateTimeParser.java
  src/main/resources/emissary/util/FlexibleDateTimeParser.cfg
  src/test/java/emissary/util/FlexibleDateTimeParserTest.java
Labels: tech-debt

#634 Add optional log checking to RegressionTest.
  src/main/java/emissary/core/IBaseDataObjectXmlHelper.java
  src/test/java/emissary/test/core/junit5/ExtractionTest.java
  src/test/java/emissary/test/core/junit5/LogbackTester.java
  src/test/java/emissary/test/core/junit5/RegressionTest.java
  src/test/java/emissary/test/core/junit5/RegressionTestUtil.java
Labels: test-only

#647 error-prone :: turn off UnnecessaryFinal
  pom.xml
Labels: tech-debt

#648 update error-prone, patterns, and compiler config
  pom.xml
Labels: dependencies, tech-debt

#650 Junit and Mockito updates
  pom.xml
Labels: dependencies

#653 LoggingPrintStreamTest Build Fixes
  src/test/java/emissary/util/io/LoggingPrintStreamTest.java
Labels: test-only
