Repository NationalSecurityAgency/emissary, pull requests merged in 2024-10, with the labels that each got.

#961 correct param for plugin.nexus-staging-maven.version
  pom.xml
Labels: BPD

#960 errorprone :: turn off InconsistentOverloads warnings
  pom.xml
Labels: BPD

#922 add ExtractedRecord object that cannot have extracted records
  src/main/java/emissary/core/DataObjectFactory.java
  src/main/java/emissary/core/ExtractedRecord.java
  src/main/java/emissary/core/IExtractedRecord.java
  src/test/java/emissary/core/DataObjectFactoryTest.java
  src/test/java/emissary/core/ExtractedRecordTest.java
Labels: framework

#969 errorprone :: StaticAssignmentOfThrowable
  src/test/java/emissary/core/BaseDataObjectTest.java
  src/test/java/emissary/util/io/LoggingPrintStreamTest.java
Labels: test-only

#968 errorprone :: Interruption
  src/main/java/emissary/core/HDMobileAgent.java
  src/main/java/emissary/core/MobileAgent.java
  src/main/java/emissary/util/shell/ReadOutputBuffer.java
  src/main/java/emissary/util/shell/ReadOutputLogger.java
  src/test/java/emissary/core/InterruptibleCharSequenceTest.java
Labels: tech-debt

#967 errorprone :: CheckedExceptionNotThrown
  src/main/java/emissary/core/channels/AbstractSeekableByteChannel.java
  src/main/java/emissary/output/filter/DataFilter.java
  src/main/java/emissary/output/filter/XmlOutputFilter.java
  src/main/java/emissary/output/roller/journal/JournaledChannelPool.java
  src/main/java/emissary/parser/SimpleNioParser.java
  src/main/java/emissary/pickup/WorkSpace.java
  src/main/java/emissary/transform/decode/HtmlEscape.java
  src/main/java/emissary/transform/decode/JavascriptEscape.java
  src/main/java/emissary/transform/decode/JsonEscape.java
  src/main/java/emissary/util/magic/MagicNumberFactory.java
Labels: tech-debt

#965 Dockerfile and docker compose updates
  .github/workflows/maven-ci.yml
  DEVELOPING.md
  contrib/docker/Dockerfile
  contrib/docker/Dockerfile.alpine
  contrib/docker/Dockerfile.ci
  contrib/docker/Dockerfile.dev
  contrib/docker/docker-compose.ci.yml
  contrib/docker/docker-compose.cluster.yml
  contrib/docker/docker-compose.server.yml
Labels: BPD

#970 errorprone :: UnusedVariable
  src/main/java/emissary/admin/Startup.java
  src/main/java/emissary/core/MetricsFormatter.java
  src/main/java/emissary/util/magic/MagicNumberFactory.java
Labels: tech-debt

#973 add new improvement label to release notes
  .github/release.yml
Labels: CI/CD

#971 errorprone: misc fixes
  src/main/java/emissary/config/ExtractResource.java
  src/main/java/emissary/core/ExtractedRecord.java
  src/main/java/emissary/place/CoordinationPlace.java
  src/main/java/emissary/util/CharsetUtil.java
Labels: tech-debt

#974 errorprone: JavaUtilDate in DropOffUtil
  src/main/java/emissary/output/DropOffUtil.java
  src/test/java/emissary/output/DropOffUtilTest.java
Labels: tech-debt

#975 errorprone: LockNotBeforeTry
  src/main/java/emissary/output/roller/journal/JournaledChannelPool.java
  src/main/java/emissary/roll/Roller.java
Labels: tech-debt

#989 fix transient DropOffUtilTest compare failure
  src/test/java/emissary/output/DropOffUtilTest.java
Labels: test-only

#976 errorprone: MissingCasesInEnumSwitch
  src/main/java/emissary/directory/DirectoryObserverManager.java
Labels: tech-debt

#986 errorprone :: ByteBufferBackingArray ignore in FillChannelFactory
  src/main/java/emissary/core/channels/FillChannelFactory.java
Labels: tech-debt

#952 updates to VersionPlace for less code-reusage downstream
  src/main/java/emissary/place/VersionPlace.java
  src/test/java/emissary/place/VersionPlaceTest.java
Labels: improvement

#983 errorprone :: ConstantField for UnixCommandPlace
  src/main/java/emissary/place/UnixCommandPlace.java
Labels: tech-debt

#985 errorprone :: ConstantField for PickUpPlace
  src/main/java/emissary/pickup/PickUpPlace.java
  src/main/java/emissary/place/MultiFileServerPlace.java
Labels: tech-debt, integration

#966 Adding listIndexOf method to KeywordScanner
  src/main/java/emissary/util/search/ByteMatcher.java
  src/main/java/emissary/util/search/KeywordScanner.java
  src/test/java/emissary/util/search/ByteMatcherTest.java
  src/test/java/emissary/util/search/KeywordScannerTest.java
Labels: feature

#992 sonarlint :: Use isEmpty() to check if collection is empty or not
  src/main/java/emissary/core/HDMobileAgent.java
  src/main/java/emissary/directory/DirectoryEntryMap.java
  src/main/java/emissary/directory/DirectoryXmlContainer.java
  src/main/java/emissary/parser/SessionProducer.java
  src/main/java/emissary/pickup/PickUpPlace.java
  src/main/java/emissary/pickup/PickUpSpace.java
  src/main/java/emissary/pool/MoveSpool.java
  src/main/java/emissary/util/magic/MagicNumberFactory.java
  src/main/java/emissary/util/search/MultiKeywordScanner.java
Labels: tech-debt

#993 errorprone :: MethodCanBeStatic
  src/main/java/emissary/server/EmissaryServer.java
Labels: tech-debt

#994 errorprone :: ThreadPriorityCheck
  src/main/java/emissary/core/MobileAgent.java
  src/main/java/emissary/core/ResourceWatcher.java
  src/main/java/emissary/core/sentinel/Sentinel.java
  src/main/java/emissary/pickup/PickUpPlace.java
  src/main/java/emissary/pickup/QueServer.java
  src/main/java/emissary/pickup/file/FileDataServer.java
  src/main/java/emissary/pickup/file/FilePickUpPlace.java
  src/main/java/emissary/pool/MoveSpool.java
  src/test/java/emissary/test/core/junit5/UnitTest.java
Labels: tech-debt

#999 errorprone :: NonFinalStaticField
  src/main/java/emissary/admin/PlaceStarter.java
  src/main/java/emissary/admin/Startup.java
  src/main/java/emissary/client/EmissaryClient.java
  src/main/java/emissary/config/ConfigUtil.java
  src/main/java/emissary/config/ServiceConfigGuide.java
  src/main/java/emissary/core/DataObjectFactory.java
  src/main/java/emissary/core/MobileAgent.java
  src/main/java/emissary/kff/EditDistance.java
  src/main/java/emissary/kff/KffChainLoader.java
  src/main/java/emissary/output/DropOffUtil.java
  src/main/java/emissary/output/filter/AbstractFilter.java
  src/main/java/emissary/place/CoordinationPlace.java
  src/main/java/emissary/pool/MoveSpool.java
  src/main/java/emissary/roll/RollManager.java
  src/main/java/emissary/server/mvc/adapters/DirectoryAdapter.java
  src/main/java/emissary/spi/JavaCharSetInitializationProvider.java
  src/main/java/emissary/spi/ObjectTracingService.java
  src/main/java/emissary/util/DateTimeFormatParser.java
  src/main/java/emissary/util/JavaCharSet.java
  src/main/java/emissary/util/PayloadUtil.java
  src/main/java/emissary/util/io/FastStringBuffer.java
  src/main/java/emissary/util/magic/MagicMath.java
  src/main/java/emissary/util/magic/MagicNumberFactory.java
  src/test/java/emissary/config/ConfigUtilTest.java
  src/test/java/emissary/core/channels/FileChannelFactoryTest.java
  src/test/java/emissary/kff/KffFileTest.java
  src/test/java/emissary/kff/KffQuincyFileTest.java
  src/test/java/emissary/server/mvc/internal/DeregisterPlaceActionTest.java
  src/test/java/emissary/server/mvc/internal/FailDirectoryActionTest.java
  src/test/java/emissary/test/core/junit5/ExtractionTest.java
  src/test/java/emissary/test/core/junit5/IdentificationTest.java
  src/test/java/emissary/util/DependencyCheckTest.java
  src/test/java/emissary/util/PayloadUtilTest.java
Labels: tech-debt

#1002 errorprone :: search UngroupedOverloads & MixedMutabilityReturnType
  src/main/java/emissary/util/search/ByteMatcher.java
  src/main/java/emissary/util/search/KeywordScanner.java
Labels: tech-debt

#998 errorprone :: CatchingUnchecked
  src/main/java/emissary/Emissary.java
  src/main/java/emissary/client/EmissaryResponse.java
  src/main/java/emissary/command/MonitorCommand.java
  src/main/java/emissary/command/TopologyCommand.java
  src/main/java/emissary/config/ServiceConfigGuide.java
  src/main/java/emissary/core/MobileAgent.java
  src/main/java/emissary/core/TimedResource.java
  src/main/java/emissary/core/sentinel/Sentinel.java
  src/main/java/emissary/directory/DirectoryPlace.java
  src/main/java/emissary/directory/HeartbeatManager.java
  src/main/java/emissary/jni/JNI.java
  src/main/java/emissary/kff/KffChainLoader.java
  src/main/java/emissary/output/DropOffPlace.java
  src/main/java/emissary/parser/ParserFactory.java
  src/main/java/emissary/pickup/PickUpSpace.java
  src/main/java/emissary/pickup/QueServer.java
  src/main/java/emissary/place/CoordinationPlace.java
  src/main/java/emissary/place/MultiFileUnixCommandPlace.java
  src/main/java/emissary/place/ServiceProviderPlace.java
  src/main/java/emissary/pool/AgentPool.java
  src/main/java/emissary/pool/MoveSpool.java
  src/main/java/emissary/pool/PayloadLauncher.java
  src/main/java/emissary/roll/RollManager.java
  src/main/java/emissary/server/api/Shutdown.java
  src/main/java/emissary/server/mvc/internal/RollOutputsAction.java
  src/main/java/emissary/transform/decode/HtmlEscape.java
  src/main/java/emissary/util/CharsetUtil.java
  src/main/java/emissary/util/DateTimeFormatParser.java
  src/main/java/emissary/util/DateTimeFormatParserLegacy.java
  src/main/java/emissary/util/DisposeHelper.java
  src/main/java/emissary/util/UnixFile.java
Labels: tech-debt

#996 errorprone :: AvoidObjectArrays
  src/main/java/emissary/admin/PlaceStarter.java
  src/main/java/emissary/client/EmissaryResponse.java
  src/main/java/emissary/config/ConfigUtil.java
  src/main/java/emissary/core/Factory.java
  src/main/java/emissary/core/IMobileAgent.java
  src/main/java/emissary/jni/JNI.java
  src/main/java/emissary/kff/ChecksumCalculator.java
  src/main/java/emissary/output/DropOffPlace.java
  src/main/java/emissary/output/DropOffUtil.java
  src/main/java/emissary/pickup/WorkSpace.java
  src/main/java/emissary/server/mvc/adapters/RequestUtil.java
  src/main/java/emissary/util/ConstructorLookupCache.java
  src/main/java/emissary/util/DataUtil.java
  src/main/java/emissary/util/magic/MagicNumber.java
  src/main/java/emissary/util/search/BackwardsTreeScanner.java
  src/main/java/emissary/util/search/FastBoyerMoore.java
  src/main/java/emissary/util/search/IMultiKeywordScanner.java
Labels: tech-debt
