Repository NationalSecurityAgency/emissary, pull requests merged in 2024-11, with the labels that each got.

#1000 errorprone :: activate
  .github/workflows/maven-ci.yml
  pom.xml
  src/main/java/emissary/core/BaseDataObject.java
  src/main/java/emissary/core/ExtractedRecord.java
  src/main/java/emissary/core/IBaseDataObject.java
  src/main/java/emissary/output/roller/JournaledCoalescer.java
  src/main/java/emissary/parser/ParserFactory.java
  src/main/java/emissary/place/MultiFileUnixCommandPlace.java
  src/main/java/emissary/transform/HtmlEscapePlace.java
  src/main/java/emissary/transform/JavascriptEscapePlace.java
  src/main/java/emissary/transform/JsonEscapePlace.java
  src/main/java/emissary/transform/decode/HtmlEscape.java
  src/main/java/emissary/transform/decode/JavascriptEscape.java
  src/main/java/emissary/transform/decode/JsonEscape.java
  src/main/java/emissary/util/shell/Executrix.java
  src/test/java/emissary/transform/HtmlEscapePlaceTest.java
  src/test/java/emissary/transform/JavascriptEscapePlaceTest.java
  src/test/java/emissary/transform/JsonEscapePlaceTest.java
  src/test/java/emissary/transform/decode/HtmlEscapeTest.java
  src/test/java/emissary/transform/decode/JsonEscapeTest.java
Labels: BPD

#1003 dependencies: bump commons-lang from 3.13.0 to 3.17.0
  pom.xml
Labels: dependencies

#1004 VersionPlace: if version is release, do not add date
  src/main/java/emissary/place/VersionPlace.java
  src/test/java/emissary/place/VersionPlaceTest.java
  src/test/resources/emissary/util/test.version.regex.git.properties
Labels: enhancement

#1008 change errorprone profile name
  pom.xml
Labels: BPD

#1010 byteutil :: add support to check for non-indexable chars
  src/main/java/emissary/util/ByteUtil.java
  src/test/java/emissary/util/ByteUtilTest.java
Labels: feature
