Repository NationalSecurityAgency/emissary, pull requests merged in 2024-06, with the labels that each got.

#809 unittest :: move StartupTest to StartupIT
  src/test/java/emissary/admin/StartupIT.java
  src/test/resources/emissary/admin/StartupIT.cfg
  src/test/resources/emissary/admin/emissary/directory/StartupIT.cfg
Labels: test-only

#812 do not generate backup poms when setting new snapshot version after r…
  .github/workflows/maven-release.yml
  .github/workflows/maven-version.yml
  .gitignore
Labels: CI/CD

#811 errorprone :: test updates
  src/test/java/emissary/EmissaryTest.java
  src/test/java/emissary/core/BaseDataObjectTest.java
  src/test/java/emissary/core/ExtendedDataObject.java
  src/test/java/emissary/core/FactoryTest.java
  src/test/java/emissary/core/HDMobileAgentBugIT.java
  src/test/java/emissary/core/InterruptibleCharSequenceTest.java
  src/test/java/emissary/core/channels/FileChannelFactoryTest.java
  src/test/java/emissary/core/channels/InMemoryChannelFactoryTest.java
  src/test/java/emissary/core/channels/SegmentChannelFactoryTest.java
  src/test/java/emissary/core/sentinel/protocols/ProtocolTest.java
  src/test/java/emissary/core/sentinel/protocols/rules/AllMaxTimeTest.java
  src/test/java/emissary/core/sentinel/protocols/rules/AnyMaxTimeTest.java
  src/test/java/emissary/kff/KffMemcachedTest.java
  src/test/java/emissary/output/roller/JournaledCoalescerTest.java
  src/test/java/emissary/parser/DecomposedSessionTest.java
  src/test/java/emissary/parser/MyDataIdentifierTest.java
  src/test/java/emissary/pickup/FTestWorkSpaceMaxBundleSize.java
  src/test/java/emissary/pickup/WorkBundleTest.java
  src/test/java/emissary/place/ComparisonPlaceTestProcessHDPlace.java
  src/test/java/emissary/place/ComparisonPlaceTestProcessPlace.java
  src/test/java/emissary/place/ServiceProviderPlaceTest.java
  src/test/java/emissary/pool/AgentPoolTest.java
  src/test/java/emissary/test/core/junit5/RegressionTest.java
  src/test/java/emissary/util/DependencyCheckTest.java
  src/test/java/emissary/util/ShortNameComparatorTest.java
  src/test/java/emissary/util/io/LoggingPrintStreamTest.java
  src/test/java/emissary/util/search/KeywordScannerTest.java
Labels: tech-debt, test-only

#814 errorprone :: revert 'static final' modifier in ServiceProviderPlaceTest
  src/test/java/emissary/place/ServiceProviderPlaceTest.java
Labels: test-only

#813 errorprone :: ClassName
  src/test/java/emissary/parser/DataIdentifierTest.java
Labels: tech-debt, test-only

#755 errorprone :: JDKObsolete Fix
  src/main/java/emissary/core/MobileAgent.java
  src/main/java/emissary/kff/KffMemcached.java
  src/main/java/emissary/output/roller/journal/JournaledChannelPool.java
  src/main/java/emissary/pickup/PickupQueue.java
  src/main/java/emissary/pickup/QueServer.java
  src/main/java/emissary/pool/MoveSpool.java
  src/main/java/emissary/server/mvc/DumpDirectoryAction.java
  src/main/java/emissary/util/MagicNumberUtil.java
  src/main/java/emissary/util/io/FileFind.java
  src/main/java/emissary/util/magic/MagicMath.java
  src/main/java/emissary/util/magic/MagicNumber.java
  src/test/java/emissary/util/shell/ExecutrixTest.java
Labels: tech-debt

#816 build :: disabled cache-to for pull requests
  .github/workflows/maven-ci.yml
  contrib/docker/Dockerfile.ci
Labels: CI/CD

#826 Modifying UnitTest so that alternative answer file location usage is thread-safe
  src/test/java/emissary/test/core/junit5/TestingResourcesTest.java
  src/test/java/emissary/test/core/junit5/UnitTest.java
Labels: bug, test-only

#770 Updating FlexibleDateTimeFormatter to cover edge cases
  src/main/java/emissary/util/FlexibleDateTimeParser.java
  src/main/resources/emissary/util/FlexibleDateTimeParser.cfg
  src/test/java/emissary/util/FlexibleDateTimeParserTest.java
Labels: priority, needs review

#831 HeartbeatManager bug fix
  src/main/java/emissary/directory/HeartbeatManager.java
Labels: bug

#821 updating RegressionTest generateAnswers for when two classes are used for test .dat & answer files
  src/test/java/emissary/test/core/junit5/RegressionTest.java
  src/test/java/emissary/test/core/junit5/RegressionTestUtil.java
  src/test/java/emissary/test/core/junit5/UnitTest.java
Labels: test-only

#833 DropOffPlace: Corrected order of Duration.between(...) arguments
  src/main/java/emissary/output/DropOffPlace.java
Labels: bug

#834 DependencyCheckTest: corrected static member initialization
  src/test/java/emissary/util/DependencyCheckTest.java
Labels: bug, test-only

#836 errorprone :: InconsistentCapitalization
  src/main/java/emissary/config/ServiceConfigGuide.java
Labels: tech-debt

#837 errorprone :: ClassesCanBeStatic
  src/main/java/emissary/server/mvc/DumpDirectoryAction.java
Labels: tech-debt
