Repository NationalSecurityAgency/emissary, pull requests merged in 2024-03, with the labels that each got.

#715 sonarlint :: HDMobileAgentBugTest
  src/test/java/emissary/core/HDMobileAgentBugTest.java
Labels: tech-debt

#720 Remove old ObjectTracing class
  src/main/java/emissary/util/ObjectTracing.java
Labels: tech-debt

#714 replace whatBin fallback method in DropOffUtil
  src/main/java/emissary/output/DropOffUtil.java
  src/test/java/emissary/output/DropOffUtilTest.java
Labels: tech-debt

#718 Add IBDO method to ensure data is available.
  src/main/java/emissary/core/BaseDataObject.java
  src/main/java/emissary/core/IBaseDataObject.java
  src/test/java/emissary/core/BaseDataObjectTest.java
Labels: enhancement

#702 github-actions :: publish site to github pages in release action
  .github/workflows/maven-release.yml
  README.md
  pom.xml
Labels: CI/CD

#725 Deprecate setFileTypeIfEmpty with array input
  src/main/java/emissary/core/BaseDataObject.java
  src/main/java/emissary/core/IBaseDataObject.java
Labels: tech-debt

#726 set unlimited maxerrs and maxwarns for error prone
  pom.xml
Labels: tech-debt

#723 update startup to use set
  src/main/java/emissary/admin/Startup.java
  src/test/java/emissary/admin/StartupTest.java
Labels: bug

#722 megalinter :: disable action applying fixes
  .github/linters/.mega-linter.yml
Labels: CI/CD
