Repository NationalSecurityAgency/emissary, pull requests merged in 2024-05, with the labels that each got.

#764 shutdown RollManager before ResourceWatcher
  src/main/java/emissary/server/EmissaryServer.java
Labels: bug

#767 fix detect-changes in ci build
  .dockerignore
  .github/workflows/maven-ci.yml
  contrib/docker/Dockerfile.ci
Labels: CI/CD

#772 errorprone :: MissingOverride & RedundantOverride
  src/main/java/emissary/core/TransformHistory.java
  src/main/java/emissary/core/sentinel/protocols/rules/AllMaxTime.java
  src/main/java/emissary/core/sentinel/protocols/rules/AnyMaxTime.java
  src/main/java/emissary/place/ServiceProviderPlace.java
  src/main/java/emissary/util/shell/Executrix.java
  src/main/java/emissary/util/shell/ProcessReader.java
  src/test/java/emissary/pickup/file/FilePickUpClientTest.java
Labels: tech-debt

#763 update trailing character cleanup regex in FlexibleDateTimeParser
  src/main/java/emissary/util/FlexibleDateTimeParser.java
  src/test/java/emissary/util/FlexibleDateTimeParserTest.java
Labels: bug

#775 sonarlint :: do not ignore InterruptedException in DelayPlace
  src/main/java/emissary/place/sample/DelayPlace.java
Labels: tech-debt

#776 sonarlint :: remove Serializable from JsonOutputFilter inner class
  src/main/java/emissary/output/filter/JsonOutputFilter.java
Labels: tech-debt

#777 errorprone :: UnusedVariable
  src/main/java/emissary/command/PeersCommand.java
  src/main/java/emissary/transform/decode/JavascriptEscape.java
  src/main/java/emissary/transform/decode/JsonEscape.java
  src/main/java/emissary/util/DataUtil.java
  src/main/java/emissary/util/WatcherThread.java
  src/main/java/emissary/util/shell/ReadOutputLogger.java
Labels: tech-debt

#774 errorprone :: EmptyCatch
  src/main/java/emissary/util/Version.java
  src/test/java/emissary/pickup/PickupQueueTest.java
  src/test/java/emissary/place/ServiceProviderPlaceTest.java
  src/test/java/emissary/test/core/junit5/FunctionalTest.java
Labels: tech-debt

#783 adding ability to pull from different directories for test data & answer files
  src/test/java/emissary/test/core/junit5/TestingResourcesTest.java
  src/test/java/emissary/test/core/junit5/UnitTest.java
  src/test/resources/emissary/test/core/junit5/TestingResourcesTest/sample.xml
Labels: enhancement, integration, test-only

#782 errorprone :: MemberName
  src/main/java/emissary/kff/EditDistance.java
  src/main/java/emissary/output/DropOffUtil.java
  src/main/java/emissary/output/roller/journal/JournalEntry.java
  src/main/java/emissary/pickup/WorkSpace.java
  src/main/java/emissary/server/EmissaryServer.java
  src/main/java/emissary/transform/decode/HtmlEscape.java
  src/main/java/emissary/util/CharsetUtil.java
  src/main/java/emissary/util/ConstructorLookupCache.java
  src/main/java/emissary/util/Entropy.java
  src/main/java/emissary/util/PkiUtil.java
Labels: tech-debt

#780 errorprone :: ThrowSpecificExceptions
  src/main/java/emissary/admin/Startup.java
  src/main/java/emissary/command/ServerCommand.java
  src/main/java/emissary/command/ServiceCommand.java
  src/main/java/emissary/core/BaseDataObject.java
  src/main/java/emissary/core/EmissaryRuntimeException.java
  src/main/java/emissary/core/Factory.java
  src/main/java/emissary/output/roller/journal/JournaledChannel.java
  src/main/java/emissary/place/ServiceProviderPlace.java
  src/main/java/emissary/server/EmissaryServer.java
  src/main/java/emissary/util/UnixFile.java
  src/main/java/emissary/util/magic/MagicNumber.java
  src/main/java/emissary/util/magic/MagicNumberFactory.java
  src/test/java/emissary/EmissaryTest.java
  src/test/java/emissary/config/ConfigUtilTest.java
  src/test/java/emissary/core/FactoryTest.java
  src/test/java/emissary/roll/RollManagerTest.java
  src/test/java/emissary/util/DisposeHelperTest.java
Labels: tech-debt

#781 errorprone :: PreferredInterfaceType
  src/main/java/emissary/output/filter/JsonOutputFilter.java
  src/main/java/emissary/output/roller/journal/JournalReader.java
  src/test/java/emissary/config/FTestServiceConfigGuide.java
  src/test/java/emissary/core/BaseDataObjectTest.java
  src/test/java/emissary/output/roller/journal/JournalTest.java
  src/test/java/emissary/test/core/junit5/ExtractionTest.java
  src/test/java/emissary/util/DataUtilTest.java
  src/test/java/emissary/util/io/UnitTestFileUtils.java
Labels: tech-debt

#806 errorprone :: InitializeInline
  src/main/java/emissary/kff/KffMemcached.java
  src/main/java/emissary/util/Entropy.java
  src/main/java/emissary/util/search/ByteMatcher.java
  src/test/java/emissary/output/DropOffUtilTest.java
  src/test/java/emissary/util/io/ResourceReaderTest.java
Labels: tech-debt

#805 errorprone :: EqualsGetClass
  src/main/java/emissary/config/ConfigEntry.java
  src/test/java/emissary/test/core/junit5/LogbackTester.java
Labels: tech-debt, test-only

#803 errorprone :: JavaTimeDefaultTimeZone
  src/main/java/emissary/output/io/DateFilterFilenameGenerator.java
  src/main/java/emissary/util/DateTimeFormatParser.java
  src/test/java/emissary/util/TimeUtilTest.java
Labels: tech-debt

#802 errorprone :: PrivateConstructorForUtilityClass
  src/main/java/emissary/spi/SPILoader.java
  src/main/java/emissary/util/DateTimeFormatParserLegacy.java
  src/main/java/emissary/util/PkiUtil.java
Labels: tech-debt

#799 errorprone :: NotJavadoc
  src/main/java/emissary/util/magic/MagicNumberFactory.java
  src/main/java/emissary/util/search/BackwardsTreeScanner.java
  src/main/java/emissary/util/web/HttpPostParameters.java
Labels: tech-debt

#795 errorprone :: ParameterMissingNullable
  src/test/java/emissary/place/ComparisonPlaceTest.java
Labels: tech-debt, test-only

#793 errorprone :: ReturnAtTheEndOfVoidFunction
  src/main/java/emissary/place/UnixCommandPlace.java
  src/main/java/emissary/util/WatcherThread.java
Labels: tech-debt

#788 errorprone :: UnnecessaryLambda
  src/test/java/emissary/util/DisposeHelperTest.java
Labels: tech-debt

#787 errorprone :: BadInstanceof -- update unit tests to use assertInstanceOf
  src/test/java/emissary/command/converter/WorkspaceSortModeConverterTest.java
  src/test/java/emissary/config/ServiceConfigGuideTest.java
  src/test/java/emissary/core/BaseDataObjectTest.java
  src/test/java/emissary/core/DataObjectFactoryTest.java
  src/test/java/emissary/core/FactoryTest.java
  src/test/java/emissary/directory/DirectoryPlaceTest.java
  src/test/java/emissary/parser/SimpleNioParserTest.java
  src/test/java/emissary/place/ServiceProviderPlaceTest.java
  src/test/java/emissary/server/mvc/EmissaryMvcTest.java
Labels: tech-debt, test-only

#807 errorprone :: ForEachIterable
  src/main/java/emissary/directory/DirectoryEntryList.java
  src/main/java/emissary/directory/DirectoryEntryMap.java
  src/main/java/emissary/pool/MoveSpool.java
Labels: tech-debt

#790 errorprone :: InterruptedExceptionSwallowed
  src/main/java/emissary/output/filter/AbstractRollableFilter.java
  src/test/java/emissary/core/FTestMovingAgent.java
  src/test/java/emissary/core/ResourceWatcherTest.java
  src/test/java/emissary/core/TimedResourceTest.java
  src/test/java/emissary/kff/KffFileTest.java
  src/test/java/emissary/output/roller/JournaledCoalescerTest.java
  src/test/java/emissary/output/roller/journal/JournaledChannelPoolTest.java
  src/test/java/emissary/roll/RollManagerTest.java
  src/test/java/emissary/test/core/junit5/UnitTest.java
  src/test/java/emissary/util/io/LoggingPrintStreamTest.java
  src/test/java/emissary/util/shell/ProcessReaderTest.java
Labels: tech-debt

#800 errorprone :: NarrowCalculation
  src/main/java/emissary/kff/Ssdeep.java
  src/test/java/emissary/core/ResourceWatcherTest.java
  src/test/java/emissary/pickup/file/FTestSpacePlaceInteraction.java
Labels: tech-debt

#792 errorprone :: StaticQualifiedUsingExpression
  src/test/java/emissary/util/ShortNameComparatorTest.java
Labels: tech-debt, test-only

#773 errorprone :: java.util.Date -> Instant
  pom.xml
  src/main/java/emissary/command/MonitorCommand.java
  src/main/java/emissary/core/BaseDataObject.java
  src/main/java/emissary/core/IBaseDataObject.java
  src/main/java/emissary/core/IBaseDataObjectHelper.java
  src/main/java/emissary/directory/HeartbeatManager.java
  src/main/java/emissary/output/DropOffPlace.java
  src/main/java/emissary/output/DropOffUtil.java
  src/main/java/emissary/output/filter/JsonOutputFilter.java
  src/main/java/emissary/util/DateTimeFormatParserLegacy.java
  src/main/java/emissary/util/PayloadUtil.java
  src/main/java/emissary/util/TimeUtil.java
  src/main/java/emissary/util/WatcherThread.java
  src/test/java/emissary/core/BaseDataObjectTest.java
  src/test/java/emissary/core/IBaseDataObjectDiffHelperTest.java
  src/test/java/emissary/core/IBaseDataObjectHelperTest.java
  src/test/java/emissary/pickup/BreakableFilePickUpClient.java
  src/test/java/emissary/util/PayloadUtilTest.java
  src/test/java/emissary/util/TimeUtilTest.java
Labels: tech-debt, integration

#786 sonarlint :: add end condition to while loop in PickUpPlace
  src/main/java/emissary/pickup/PickUpPlace.java
Labels: tech-debt

#785 errorprone :: SystemExitOutsideMain
  src/main/java/emissary/admin/PlaceStarter.java
  src/main/java/emissary/core/sentinel/protocols/actions/Exit.java
  src/main/java/emissary/output/filter/AbstractRollableFilter.java
  src/main/java/emissary/roll/RollManager.java
  src/main/java/emissary/server/api/Shutdown.java
Labels: tech-debt

#789 errorprone :: UnnecessaryDefaultInEnumSwitch
  src/main/java/emissary/core/BaseDataObject.java
Labels: tech-debt
