Repository NationalSecurityAgency/emissary, pull requests merged in 2024-02, with the labels that each got.

#658 Improve SegmentChannelFactory testing.
  src/main/java/emissary/core/channels/SegmentChannelFactory.java
  src/test/java/emissary/core/channels/SegmentChannelFactoryTest.java
Labels: tech-debt

#570 remove deprecated timeutil methods
  src/main/java/emissary/output/DropOffUtil.java
  src/main/java/emissary/util/TimeUtil.java
  src/test/java/emissary/util/TimeUtilTest.java
Labels: tech-debt

#662 Update action versions for deprecated Node.js
  .github/workflows/cherrypick.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/create-patch-branch.yml
  .github/workflows/dependency-review.yml
  .github/workflows/linter.yaml
  .github/workflows/maven-ci.yml
  .github/workflows/maven-publish.yml
  .github/workflows/maven-release.yml
  .github/workflows/maven-version.yml
Labels: dependencies, CI/CD

#649 Updating jackson dependencies to 2.15.2
  pom.xml
Labels: dependencies

#673 guava 32.0.0-jre -> 32.1.2-jre
  pom.xml
Labels: dependencies

#675 commons-lang 3.12.0 -> 3.13.0
  pom.xml
Labels: dependencies

#657 Improve IBaseDataObjectHelper testing.
  src/main/java/emissary/core/IBaseDataObjectHelper.java
  src/test/java/emissary/core/IBaseDataObjectHelperTest.java
Labels: tech-debt

#685 Remove deprecated defaultString()
  src/main/java/emissary/core/sentinel/Sentinel.java
Labels: tech-debt

#664 Fix SONAR warnings for IBaseDataObjectDiffHelper.
  src/main/java/emissary/core/IBaseDataObjectDiffHelper.java
Labels: tech-debt

#652 Resolving error-prone MemberNames
  src/main/java/emissary/client/response/Directory.java
  src/main/java/emissary/core/HDMobileAgent.java
  src/main/java/emissary/core/IMobileAgent.java
  src/main/java/emissary/core/MobileAgent.java
  src/main/java/emissary/core/sentinel/Sentinel.java
  src/main/java/emissary/directory/DirectoryEntry.java
  src/main/java/emissary/directory/DirectoryEntryList.java
  src/main/java/emissary/directory/DirectoryEntryMap.java
  src/main/java/emissary/directory/DirectoryPlace.java
  src/main/java/emissary/directory/HeartbeatManager.java
  src/main/java/emissary/directory/KeyManipulator.java
  src/main/java/emissary/place/CoordinationPlace.java
  src/main/java/emissary/place/IServiceProviderPlace.java
  src/main/java/emissary/place/ServiceProviderPlace.java
  src/main/java/emissary/server/mvc/DumpDirectoryAction.java
  src/main/java/emissary/server/mvc/adapters/DirectoryAdapter.java
  src/main/java/emissary/server/mvc/adapters/WorkSpaceAdapter.java
  src/test/java/emissary/core/BogusHDAgent.java
  src/test/java/emissary/core/FTestMovingAgent.java
  src/test/java/emissary/core/ResourceWatcherTest.java
  src/test/java/emissary/core/sentinel/SentinelTest.java
  src/test/java/emissary/directory/DirectoryEntryListTest.java
  src/test/java/emissary/directory/DirectoryEntryTest.java
  src/test/java/emissary/directory/KeyManipulatorTest.java
Labels: tech-debt

#686 Addressing auto-closeable warnings
  src/test/java/emissary/core/channels/AbstractSeekableByteChannelTest.java
  src/test/java/emissary/core/channels/FileChannelFactoryTest.java
  src/test/java/emissary/core/channels/InputStreamChannelFactoryTest.java
Labels: test-only

#687 Adressed unreferenced auto-closeable resources
  src/test/java/emissary/core/ResourceWatcherTest.java
  src/test/java/emissary/core/channels/SegmentChannelFactoryTest.java
  src/test/java/emissary/util/io/ListOpenFilesTest.java
  src/test/java/emissary/util/roll/RollableFileOutputStreamTest.java
Labels: test-only

#678 commons-codec 1.15 -> 1.16.0
  pom.xml
Labels: dependencies

#684 Address error-prone ReturnMissingNullable and FieldMissingNullable
  src/main/java/emissary/client/EmissaryClient.java
  src/main/java/emissary/client/EmissaryResponse.java
  src/main/java/emissary/command/BaseCommand.java
  src/main/java/emissary/core/MobileAgent.java
  src/main/java/emissary/core/Stage.java
  src/main/java/emissary/core/TimedResource.java
  src/main/java/emissary/core/TransformHistory.java
  src/main/java/emissary/directory/DirectoryEntry.java
  src/main/java/emissary/kff/ChecksumResults.java
  src/main/java/emissary/pickup/PickUpPlace.java
  src/main/java/emissary/pickup/WorkBundle.java
  src/main/java/emissary/place/ServiceProviderPlace.java
  src/main/java/emissary/place/sample/CachePlace.java
  src/main/java/emissary/util/magic/MagicNumberFactory.java
  src/test/java/emissary/admin/StartupTest.java
  src/test/java/emissary/command/PeersCommandIT.java
  src/test/java/emissary/command/converter/WorkspaceSortModeConverterTest.java
  src/test/java/emissary/config/ConfigUtilTest.java
  src/test/java/emissary/core/BogusHDAgent.java
  src/test/java/emissary/core/FTestMovingAgent.java
  src/test/java/emissary/core/TimedResourceTest.java
  src/test/java/emissary/directory/DirectoryEntryMapTest.java
  src/test/java/emissary/directory/DirectoryEntryTest.java
  src/test/java/emissary/id/IdPlaceTest.java
  src/test/java/emissary/output/filter/XmlOutputFilterTest.java
  src/test/java/emissary/output/roller/journal/JournaledChannelTest.java
  src/test/java/emissary/parser/SimpleNioParserTest.java
  src/test/java/emissary/pickup/file/FilePickUpClientTest.java
  src/test/java/emissary/place/ServiceProviderPlaceTest.java
  src/test/java/emissary/server/mvc/internal/DeregisterPlaceActionTest.java
  src/test/java/emissary/server/mvc/internal/FailDirectoryActionTest.java
  src/test/java/emissary/test/core/junit5/ExtractionTest.java
  src/test/java/emissary/test/core/junit5/FunctionalTest.java
  src/test/java/emissary/test/core/junit5/LogbackTester.java
  src/test/java/emissary/test/core/junit5/RegressionTestUtil.java
  src/test/java/emissary/test/core/junit5/UnitTest.java
  src/test/java/emissary/util/shell/ExecutrixTest.java
  src/test/java/emissary/util/shell/ProcessReaderTest.java
Labels: tech-debt

#674 gson 2.8.9 -> 2.10.1
  pom.xml
Labels: dependencies

#677 commons-io 2.11.0 -> 2.13.0
  pom.xml
Labels: dependencies

#670 Adding Convenience Method to Configurator interface / ServiceConfigGuide class
  src/main/java/emissary/config/Configurator.java
  src/main/java/emissary/config/ServiceConfigGuide.java
  src/test/java/emissary/config/ServiceConfigGuideTest.java
Labels: enhancement

#676 commons-compress 1.21 -> 1.24.0
  pom.xml
Labels: dependencies

#654 removing SystemOut error-prone warnings
  src/main/java/emissary/directory/KeyManipulator.java
  src/test/java/emissary/EmissaryTest.java
Labels: tech-debt

#695 use bom for io.dropwizard.metrics versions
  pom.xml
Labels: tech-debt

#671 add plugin to generate sbom
  pom.xml
Labels: feature

#679 Updated RegressionTest to generate answers from command line
  src/test/java/emissary/test/core/junit5/RegressionTest.java
Labels: test-only

#689 update variable names in StartupTest
  src/test/java/emissary/admin/StartupTest.java
Labels: test-only

#681 Removed Deprecated checkLogList Method
  src/test/java/emissary/core/BaseDataObjectTest.java
  src/test/java/emissary/core/SafeUsageCheckerTest.java
  src/test/java/emissary/test/core/junit5/LogbackTester.java
  src/test/java/emissary/test/core/junit5/LogbackTesterTest.java
Labels: test-only

#665 Fix SONAR warning in IBaseDataObjectXmlCodecs.
  src/main/java/emissary/core/IBaseDataObjectXmlCodecs.java
  src/main/java/emissary/core/IBaseDataObjectXmlHelper.java
  src/test/java/emissary/core/IBaseDataObjectDiffHelperTest.java
Labels: tech-debt

#683 Normalize actions with internal project and add slack notifications
  .github/workflows/dependency-review.yml
  .github/workflows/maven-ci.yml
  .github/workflows/maven-release.yml
  .github/workflows/maven-version.yml
Labels: CI/CD

#656 Remove IBaseDataObjectHelper.setPrivateFieldValue() method.
  src/main/java/emissary/core/IBaseDataObjectHelper.java
  src/main/java/emissary/core/IBaseDataObjectXmlHelper.java
  src/test/java/emissary/core/IBaseDataObjectHelperTest.java
  src/test/java/emissary/core/IBaseDataObjectXmlHelperTest.java
  src/test/java/emissary/test/core/junit5/RegressionTest.java
  src/test/java/emissary/test/core/junit5/RegressionTestUtil.java
Labels: tech-debt

#700 Fix get version for maven-release.yml action
  .github/workflows/maven-release.yml
Labels: CI/CD

#560 remove deprecated directoryplace constructors
  src/main/java/emissary/admin/PlaceStarter.java
  src/main/java/emissary/admin/Startup.java
  src/main/java/emissary/directory/DirectoryPlace.java
Labels: tech-debt

#704 Update RegressionTest difference output style.
  src/test/java/emissary/test/core/junit5/RegressionTestUtil.java
Labels: test-only

#696 New method to copy metadata from parent to child with exclusions
  src/main/java/emissary/core/IBaseDataObjectHelper.java
  src/test/java/emissary/core/IBaseDataObjectHelperTest.java
Labels: enhancement

#708 resolve error-prone MissingBraces
  src/main/java/emissary/util/magic/MagicNumber.java
  src/main/java/emissary/util/magic/MagicNumberFactory.java
  src/test/java/emissary/pickup/file/FilePickUpClientTest.java
  src/test/java/emissary/test/core/junit5/LogbackTester.java
Labels: tech-debt

#701 github-actions :: version in env, slack-bot message format
  .github/workflows/maven-release.yml
Labels: CI/CD

#707 Deprecate IBDO.clone()/BDO.clone() in preparation for deletion per Sonar warning
  src/main/java/emissary/core/BaseDataObject.java
  src/main/java/emissary/core/IBaseDataObject.java
Labels: tech-debt

#632 EmissaryServer shutdown when unannounced places are started in strict-mode
  src/main/java/emissary/admin/Startup.java
  src/main/java/emissary/server/EmissaryServer.java
  src/test/java/emissary/admin/StartupTest.java
  src/test/java/emissary/server/EmissaryServerIT.java
Labels: enhancement, integration

#669 Have strict server shutdown when CoordinationPlace place fails to create/DNE
  src/main/java/emissary/admin/Startup.java
  src/main/java/emissary/place/CoordinationPlace.java
  src/test/java/emissary/place/CoordinationPlaceTest.java
Labels: enhancement

#713 Excluding BooleanParameter from error-prone warnings
  pom.xml
Labels: tech-debt
