Repository NationalSecurityAgency/emissary, pull requests merged in 2024-08, with the labels that each got.

#865 errorprone :: ConstantField - EmissaryClient.context
  src/main/java/emissary/client/EmissaryClient.java
  src/main/java/emissary/directory/HeartbeatManager.java
  src/main/java/emissary/server/mvc/adapters/DirectoryAdapter.java
  src/main/java/emissary/server/mvc/adapters/WorkSpaceAdapter.java
  src/test/java/emissary/core/FTestMovingAgent.java
Labels: tech-debt

#863 errorprone :: ConstantField - core classes
  src/main/java/emissary/command/Banner.java
  src/main/java/emissary/command/EnvCommand.java
  src/main/java/emissary/core/BaseDataObject.java
  src/main/java/emissary/core/DataObjectFactory.java
  src/main/java/emissary/core/MobileAgent.java
  src/main/java/emissary/parser/ParserFactory.java
  src/main/java/emissary/pool/MobileAgentFactory.java
  src/main/java/emissary/roll/RollManager.java
  src/main/java/emissary/server/mvc/TransferDirectoryAction.java
  src/test/java/emissary/core/ExtendedDataObject.java
Labels: tech-debt

#864 errorprone :: ConstantField - more core classes
  src/main/java/emissary/command/AgentsCommand.java
  src/main/java/emissary/command/ConfigCommand.java
  src/main/java/emissary/command/TopologyCommand.java
  src/main/java/emissary/config/ServiceConfigGuide.java
  src/main/java/emissary/pickup/PickUpSpace.java
  src/main/java/emissary/pickup/file/FileDataServer.java
  src/main/java/emissary/pickup/file/FilePickUpPlace.java
  src/test/java/emissary/place/ServiceProviderPlaceTest.java
Labels: tech-debt

#861 update transform history to store coordinated places as array list
  src/main/java/emissary/core/BaseDataObject.java
  src/main/java/emissary/core/TransformHistory.java
  src/main/java/emissary/util/PayloadUtil.java
  src/test/java/emissary/core/TransformHistoryTest.java
Labels: framework, priority

#866 Remove tech-debt from 'Improvement' release reporting
  .github/release.yml
Labels: CI/CD

#868 revert MemberName change to ObjectTracing.Stage enum
  src/main/java/emissary/pickup/PickUpPlace.java
  src/main/java/emissary/spi/ObjectTracing.java
Labels: patch

#877 refactor CoordinationPlace to improve extensibility and reduce complexity
  src/main/java/emissary/place/CoordinationPlace.java
Labels: enhancement

#875 errorprone :: ConstantField - UnitTest.TMPDIR
  src/test/java/emissary/test/core/junit5/UnitTest.java
Labels: tech-debt, test-only

#874 errorprone :: ConstantField - Emissary.EMISSARY_COMMANDS
  src/main/java/emissary/Emissary.java
Labels: tech-debt

#884 Deprecate IBDO/BDO ByteBuffer methods.
  src/main/java/emissary/core/BaseDataObject.java
  src/main/java/emissary/core/IBaseDataObject.java
Labels: tech-debt

#882 deprecating HtmlEscapePlace and HtmlEscape utility
  src/main/java/emissary/transform/HtmlEscapePlace.java
  src/main/java/emissary/transform/decode/HtmlEscape.java
  src/test/java/emissary/transform/HtmlEscapePlaceTest.java
  src/test/java/emissary/transform/decode/HtmlEscapeTest.java
Labels: tech-debt

#881 deprecating JavascriptEscapePlace and JavascriptEscape utility
  src/main/java/emissary/transform/JavascriptEscapePlace.java
  src/main/java/emissary/transform/decode/JavascriptEscape.java
  src/test/java/emissary/transform/JavascriptEscapePlaceTest.java
Labels: tech-debt

#878 warn during startup when class string is not unique
  src/main/java/emissary/admin/PlaceStarter.java
  src/main/java/emissary/admin/Startup.java
Labels: enhancement

#872 errorprone :: ConstantField
  src/main/java/emissary/command/ServiceCommand.java
  src/main/java/emissary/id/SizeIdPlace.java
  src/main/java/emissary/kff/KffChain.java
  src/main/java/emissary/kff/Ssdeep.java
  src/main/java/emissary/parser/DataIdentifier.java
  src/main/java/emissary/parser/SessionParser.java
  src/main/java/emissary/place/MultiFileServerPlace.java
  src/main/java/emissary/place/MultiFileUnixCommandPlace.java
  src/main/java/emissary/util/search/Hit.java
  src/test/java/emissary/config/ConfigUtilTest.java
  src/test/java/emissary/place/RehashingPlaceTest.java
Labels: tech-debt

#885 Suppress server startup attempt when trying to pause a non-responsive server
  src/main/java/emissary/command/ServiceCommand.java
Labels: enhancement

#876 Add ConcatenateChannelFactory for seekable byte channels
  src/main/java/emissary/core/channels/ConcatenateChannelFactory.java
  src/test/java/emissary/core/channels/CheckCloseChannelFactory.java
  src/test/java/emissary/core/channels/ConcatenateChannelFactoryTest.java
  src/test/java/emissary/core/channels/ExceptionChannelFactory.java
  src/test/java/emissary/core/channels/SegmentChannelFactoryTest.java
Labels: enhancement

#871 reduce transform history output
  src/main/java/emissary/core/TransformHistory.java
  src/main/java/emissary/util/PayloadUtil.java
  src/main/resources/emissary/util/PayloadUtil.cfg
  src/test/java/emissary/core/TransformHistoryTest.java
  src/test/java/emissary/util/PayloadUtilTest.java
Labels: enhancement, activation

#886 Preserving the Original MD5 if the payload is hashed more than once
  src/main/java/emissary/kff/KffDataObjectHandler.java
  src/test/java/emissary/kff/KffDataObjectHandlerTest.java
Labels: integration, activation

#887 building out VersionPlace to add emissary version info to metadata
  src/main/config/emissary.admin.ClassNameInventory.cfg
  src/main/config/places.cfg
  src/main/java/emissary/place/VersionPlace.java
  src/main/resources/emissary/place/VersionPlace.cfg
  src/test/java/emissary/place/VersionPlaceTest.java
  src/test/resources/emissary/place/VersionPlaceTest.cfg
Labels: feature, activation

#898 VersionPlace - add EMISSARY_VERSION_HASH to metadata
  src/main/java/emissary/place/VersionPlace.java
  src/main/java/emissary/util/GitRepositoryState.java
  src/main/resources/emissary/place/VersionPlace.cfg
  src/test/java/emissary/place/VersionPlaceTest.java
Labels: enhancement

#844 errorprone :: change casing of Kff FilterType enum
  src/main/java/emissary/kff/KffChainLoader.java
  src/main/java/emissary/kff/KffFile.java
  src/main/java/emissary/kff/KffFilter.java
  src/main/java/emissary/kff/KffMemcached.java
  src/main/java/emissary/kff/KffQuincyFile.java
  src/main/java/emissary/kff/KffResult.java
  src/test/java/emissary/kff/KffFileTest.java
  src/test/java/emissary/kff/KffMemcachedTest.java
  src/test/java/emissary/kff/KffQuincyFileTest.java
Labels: tech-debt, integration

#846 errorprone :: MemberName - CharsetUtil
  src/main/java/emissary/util/CharsetUtil.java
  src/test/java/emissary/util/CharsetUtilTest.java
Labels: tech-debt, integration

#856 errorprone :: MemberName - util package
  src/main/java/emissary/transform/decode/HtmlEscape.java
  src/main/java/emissary/util/CharacterCounterSet.java
  src/main/java/emissary/util/HtmlEntityMap.java
  src/main/java/emissary/util/search/Hit.java
  src/test/java/emissary/util/search/MultiKeywordScannerTest.java
Labels: tech-debt, integration

#870 errorprone :: MemberName - ObjectTracing
  src/main/java/emissary/pickup/PickUpPlace.java
  src/main/java/emissary/spi/ObjectTracing.java
Labels: tech-debt, integration

#873 errorprone :: ConstantField - WorkSpace
  src/main/java/emissary/pickup/WorkSpace.java
  src/test/java/emissary/pickup/FTestWorkSpaceMaxBundleSize.java
Labels: tech-debt, integration

#892 errorprone :: FieldCanBeFinal
  src/main/java/emissary/admin/Startup.java
  src/main/java/emissary/client/EmissaryClient.java
  src/main/java/emissary/command/converter/FileExistsConverter.java
  src/main/java/emissary/command/converter/PathExistsConverter.java
  src/main/java/emissary/core/DiffCheckConfiguration.java
  src/main/java/emissary/core/channels/InputStreamChannelFactory.java
  src/main/java/emissary/kff/ChecksumCalculator.java
  src/main/java/emissary/kff/KffFile.java
  src/main/java/emissary/kff/KffMemcached.java
  src/main/java/emissary/kff/SpamSumSignature.java
  src/main/java/emissary/output/filter/JsonOutputFilter.java
  src/main/java/emissary/output/io/SimpleFileNameGenerator.java
  src/main/java/emissary/output/roller/JournaledCoalescer.java
  src/main/java/emissary/util/CaseInsensitiveMap.java
  src/main/java/emissary/util/UnixFile.java
  src/main/java/emissary/util/io/FileFind.java
  src/main/java/emissary/util/io/ReadOutput.java
  src/main/java/emissary/util/roll/RollableFileOutputStream.java
  src/main/java/emissary/util/search/ByteTokenizer.java
  src/main/java/emissary/util/search/KeywordScanner.java
  src/main/java/emissary/util/search/MultiKeywordScanner.java
Labels: tech-debt

#891 errorprone :: MultipleTopLevelClasses
  src/test/java/emissary/command/BaseCommandTest.java
Labels: tech-debt

#890 errorprone :: MutablePublicArray
  src/main/java/emissary/util/CharacterCounterSet.java
  src/main/java/emissary/util/ThreadDump.java
  src/test/java/emissary/command/FeedCommandIT.java
  src/test/java/emissary/util/CharsetUtilTest.java
Labels: tech-debt

#857 errorprone :: MemberName
  src/main/java/emissary/config/ServiceConfigGuide.java
  src/main/java/emissary/core/HDMobileAgent.java
  src/main/java/emissary/place/ServiceProviderPlace.java
  src/test/java/emissary/place/ServiceProviderPlaceGetTLDTest.java
Labels: tech-debt, integration

#852 errorprone :: MemberName - kff package
  src/main/java/emissary/kff/ChecksumCalculator.java
  src/main/java/emissary/kff/EditDistance.java
  src/main/java/emissary/kff/SpamSumSignature.java
  src/main/java/emissary/kff/Ssdeep.java
  src/test/java/emissary/kff/ChecksumCalculatorTest.java
  src/test/java/emissary/kff/KffMemcachedTest.java
  src/test/java/emissary/kff/SsdeepTest.java
Labels: tech-debt, integration

#903 sync commit message and PR title for next development release
  .github/workflows/maven-release.yml
Labels: CI/CD
