Repository NationalSecurityAgency/emissary, pull requests merged in 2025-09, with the labels that each got.

#1178 remove RegressionTestAnswerGenerator logger call from AnswerGenerator
  src/test/java/emissary/test/core/junit5/AnswerGenerator.java
Labels: tech-debt

#1172 adding OS specific checks to attachment elements in ExtractionTest
  src/test/java/emissary/test/core/junit5/ExtractionTest.java
  src/test/resources/emissary/test/core/junit5/OsSpecificTest.xml
  src/test/resources/emissary/test/core/schemas/answers.xsd
Labels: enhancement, test-only

#1190 change version command output to include git hash
  src/main/java/emissary/Emissary.java
  src/main/java/emissary/command/VersionCommand.java
  src/main/java/emissary/server/api/Version.java
  src/main/java/emissary/util/GitRepositoryState.java
Labels: enhancement
