Repository NationalSecurityAgency/emissary, pull requests merged in 2025-06, with the labels that each got.

#1135 tests :: update answers schema to add length element to view
  src/test/resources/emissary/test/core/schemas/answers.xsd
Labels: test-only

#1137 tests :: add schema for regression test answers
  src/test/java/emissary/test/core/junit5/RegressionTest.java
  src/test/java/emissary/test/core/junit5/UnitTest.java
  src/test/resources/emissary/test/core/schemas/regression.xsd
  src/test/resources/emissary/test/core/schemas/xml.xsd
Labels: integration, test-only

#1142 Reformatted gRPC connection factory
  src/main/java/emissary/grpc/exceptions/PoolException.java
  src/main/java/emissary/grpc/exceptions/ServiceException.java
  src/main/java/emissary/grpc/exceptions/ServiceNotAvailableException.java
  src/main/java/emissary/grpc/exceptions/ServiceNotLiveException.java
  src/main/java/emissary/grpc/exceptions/ServiceNotReadyException.java
  src/main/java/emissary/grpc/pool/ConnectionFactory.java
  src/main/java/emissary/grpc/pool/LoadBalancingPolicy.java
  src/main/java/emissary/grpc/pool/PoolRetrievalOrdering.java
  src/main/java/emissary/util/grpc/pool/ConnectionDefaults.java
  src/test/java/emissary/grpc/exceptions/ServiceExceptionTest.java
  src/test/java/emissary/grpc/pool/ConnectionFactoryTest.java
  src/test/java/emissary/util/grpc/pool/ConnectionFactoryTest.java
Labels: improvement

#1146 fix docker build
  contrib/docker/Dockerfile
Labels: CI/CD

#1147 gRPC connection factory additional formatting changes
  src/main/java/emissary/grpc/pool/ConnectionFactory.java
  src/test/java/emissary/grpc/pool/ConnectionFactoryTest.java
Labels: enhancement

#1150 docker-ci :: ubi8 fixes
  contrib/docker/Dockerfile
Labels: CI/CD

#1152 regression-test :: flatten RegressionTest and RegressionTestUtil
  src/test/java/emissary/test/core/junit5/LogbackTester.java
  src/test/java/emissary/test/core/junit5/RegressionTest.java
  src/test/java/emissary/test/core/junit5/RegressionTestUtil.java
Labels: test-only
