Repository NationalSecurityAgency/emissary, pull requests merged in 2025-01, with the labels that each got.

#1038 update methods in OSReleaseUtil
  src/main/java/emissary/util/os/OSReleaseUtil.java
  src/test/java/emissary/util/os/OSReleaseUtilTest.java
  src/test/resources/emissary/util/os/ubuntu20
Labels: enhancement

#1024 initialize static instance of EmissaryServer
  src/main/java/emissary/admin/Startup.java
  src/main/java/emissary/command/ServerCommand.java
  src/main/java/emissary/directory/EmissaryNode.java
  src/main/java/emissary/pickup/WorkSpace.java
  src/main/java/emissary/place/ServiceProviderPlace.java
  src/main/java/emissary/server/EmissaryServer.java
  src/test/java/emissary/server/EmissaryServerIT.java
  src/test/java/emissary/server/api/PeersIT.java
  src/test/java/emissary/test/core/junit5/FunctionalTest.java
  src/test/java/emissary/test/core/junit5/UnitTest.java
Labels: framework, improvement

#1016 Adding support to link a tld to a child IBDO for inheriting parameters
  src/main/java/emissary/core/BaseDataObject.java
  src/main/java/emissary/core/DataObjectFactory.java
  src/main/java/emissary/core/IBaseDataObject.java
  src/test/java/emissary/core/BaseDataObjectTest.java
  src/test/java/emissary/core/DataObjectFactoryTest.java
Labels: framework, priority

#1045 getStringParameter deprecation should suggest getParameterAsString
  src/main/java/emissary/core/IBaseDataObject.java
Labels: documentation

#1044 Adding a utility to provide test data for specific unicode handling issues.
  pom.xml
  src/test/java/emissary/test/util/ComplexUnicodeSamples.java
  src/test/java/emissary/test/util/ComplexUnicodeSamplesTest.java
Labels: dependencies, feature

#1037 Added cleaner Executrix temp file names API, deprecated array-based API
  src/main/java/emissary/place/MultiFileUnixCommandPlace.java
  src/main/java/emissary/place/UnixCommandPlace.java
  src/main/java/emissary/util/shell/Executrix.java
  src/main/java/emissary/util/shell/TempFileNames.java
  src/test/java/emissary/util/shell/ExecutrixTest.java
Labels: improvement

#1047 fallback to original behavior for getParameterAsString
  src/main/java/emissary/core/BaseDataObject.java
  src/test/java/emissary/core/BaseDataObjectTest.java
Labels: improvement

#1048 errorprone :: fail build on warnings/errors
  pom.xml
Labels: BPD

#1042 change EmissaryServer to use an enum for mode
  src/main/java/emissary/command/ServerCommand.java
  src/main/java/emissary/command/converter/ModeConverter.java
  src/main/java/emissary/command/validator/ServerModeValidator.java
  src/main/java/emissary/command/validator/package-info.java
  src/main/java/emissary/directory/EmissaryNode.java
  src/test/java/emissary/server/api/PeersIT.java
Labels: improvement

#1049 deprecate SUFFIXES_HTML_ESCAPE constant parameter
  src/main/java/emissary/core/constants/Parameters.java
Labels: tech-debt

#1041 Add RegularExpresionTestUtil for testing regexes
  src/test/java/emissary/test/util/RegularExpressionTestUtil.java
Labels: feature, test-only

#1052 TempFileNames constructor is now public, not package-private
  src/main/java/emissary/util/shell/TempFileNames.java
Labels: improvement

#1053 pmd :: UnnecessarySemicolon
  src/main/java/emissary/core/IBaseDataObject.java
  src/test/java/emissary/core/channels/ChannelTestHelper.java
Labels: tech-debt
