Repository NationalSecurityAgency/emissary, pull requests merged in 2025-03, with the labels that each got.

#1078 add custom pmd rule config
  contrib/pmd/maven-pmd-plugin-default.xml
  pom.xml
Labels: BPD

#1079 add undeclared deps, remove unused deps, tidy up management
  pom.xml
Labels: BPD

#1074 adding ability to ExtractionTest to have OS specific answers in test answer files
  src/test/java/emissary/test/core/junit5/ExtractionTest.java
  src/test/java/emissary/test/core/junit5/TestExtractionTest.java
  src/test/resources/emissary/test/core/junit5/OsSpecificTest.xml
Labels: test-only

#1075 Update PlaceComparisonHelper to compare "dispose runnables".
  src/main/java/emissary/util/PlaceComparisonHelper.java
Labels: test-only

#1077 allow RegressionTest getEncoders/getDecoders to vary per "resource"
  src/test/java/emissary/test/core/junit5/RegressionTest.java
Labels: test-only

#1076 Reverse New/Old IBDO output to match input order in PlaceComparisonHelper.
  src/main/java/emissary/util/PlaceComparisonHelper.java
  src/test/java/emissary/place/ComparisonPlaceTest.java
Labels: test-only

#1086 expose the ability to choose SBCF/byte[] for addParentInformation...()
  src/main/java/emissary/core/IBaseDataObjectHelper.java
Labels: improvement

#1090 enforce analyzed compile scope dependencies
  pom.xml
  src/assembly/dist.xml
Labels: BPD

#1073 refresh :: "light" and "hard" refresh logic
  src/main/config/emissary.admin.ClassNameInventory.cfg
  src/main/config/emissary.place.sample.RefreshablePlace.cfg
  src/main/config/places.cfg
  src/main/java/emissary/command/ServerCommand.java
  src/main/java/emissary/command/ServiceCommand.java
  src/main/java/emissary/directory/DirectoryEntry.java
  src/main/java/emissary/directory/DirectoryPlace.java
  src/main/java/emissary/directory/EmissaryNode.java
  src/main/java/emissary/place/ServiceProviderPlace.java
  src/main/java/emissary/place/ServiceProviderRefreshablePlace.java
  src/main/java/emissary/place/sample/RefreshablePlace.java
  src/main/java/emissary/server/EmissaryServer.java
  src/main/java/emissary/server/api/Refresh.java
  src/test/java/emissary/place/ServiceProviderRefreshablePlaceTest.java
  src/test/resources/emissary/place/RefreshablePlaceTest.cfg
Labels: discussion, feature, activation

#1089 regression :: pulled some of the SimplifiedLogEvent logic up to ExtractionTest
  src/test/java/emissary/test/core/junit5/ExtractionTest.java
  src/test/java/emissary/test/core/junit5/RegressionTest.java
Labels: test-only

#1088 regression :: updated IbdoMethodNames to use BiConsumers
  src/main/java/emissary/core/IBaseDataObjectXmlCodecs.java
  src/main/java/emissary/core/constants/IbdoMethodNames.java
  src/test/java/emissary/core/IBaseDataObjectDiffHelperTest.java
Labels: enhancement

#1093 add script to create a tarball of the git repo
  contrib/repo-manual-mirror.sh
Labels: BPD

#1092 enforce analyzed test scope dependencies
  pom.xml
  src/test/java/emissary/server/mvc/EndpointTestBase.java
Labels: BPD
