Repository NationalSecurityAgency/emissary, pull requests merged in 2025-04, with the labels that each got.

#1094 regression-test :: add default method to fix dispose runnables
  src/test/java/emissary/test/core/junit5/RegressionTest.java
Labels: test-only

#1096 regression-test :: move ibdo xml code to test
  src/test/java/emissary/core/IBaseDataObjectXmlCodecs.java
  src/test/java/emissary/core/IBaseDataObjectXmlHelper.java
Labels: test-only

#1097 regression-test :: move comparison code to test
  src/test/java/emissary/core/DiffCheckConfiguration.java
  src/test/java/emissary/core/IBaseDataObjectDiffHelper.java
  src/test/java/emissary/place/ComparisonPlace.java
  src/test/java/emissary/util/PlaceComparisonHelper.java
Labels: test-only

#1100 pmd :: UselessParentheses
  src/main/java/emissary/kff/Ssdeep.java
  src/main/java/emissary/transform/decode/JsonEscape.java
  src/main/java/emissary/util/Hexl.java
  src/main/java/emissary/util/xml/AbstractJDOMUtil.java
Labels: tech-debt

#1095 pmd :: UnnecessaryFullyQualifiedNames
  contrib/pmd/maven-pmd-plugin-default.xml
  src/main/java/emissary/util/DependencyCheck.java
  src/test/java/emissary/client/HTTPConnectionFactoryTest.java
  src/test/java/emissary/test/core/junit5/TestExtractionTest.java
  src/test/java/emissary/util/FlexibleDateTimeParserTest.java
Labels: tech-debt

#1102 extraction-test :: add support for mac os-release
  src/main/java/emissary/util/os/OSReleaseUtil.java
  src/test/java/emissary/test/core/junit5/ExtractionTest.java
  src/test/java/emissary/test/core/junit5/TestExtractionTest.java
  src/test/resources/emissary/test/core/junit5/OsSpecificTest.xml
Labels: enhancement

#1109 code clean-up in MagicNumberFactory
  src/main/java/emissary/util/magic/MagicNumberFactory.java
Labels: tech-debt

#1103 pmd :: UnusedPrivateMethod
  src/main/java/emissary/kff/KffFile.java
  src/main/java/emissary/util/magic/MagicNumber.java
Labels: tech-debt

#1105 pmd :: UnusedFormalParameter
  src/main/java/emissary/kff/KffMemcached.java
  src/main/java/emissary/place/ServiceProviderPlace.java
  src/test/java/emissary/core/FTestMobileAgent.java
  src/test/java/emissary/pickup/BreakableFilePickUpClient.java
  src/test/java/emissary/place/OOMPlace.java
  src/test/java/emissary/test/core/junit5/UnitTest.java
Labels: tech-debt

#1112 remove maven site publish from release workflow
  .github/workflows/maven-release.yml
Labels: CI/CD

#1111 pmd :: CollapsibleIfStatement
  src/main/java/emissary/kff/Ssdeep.java
  src/main/java/emissary/roll/Roller.java
Labels: tech-debt

#1110 pmd :: AvoidBranchingStatementAsLastInLoop
  src/main/java/emissary/directory/DirectoryPlace.java
  src/main/java/emissary/jni/JniRepositoryPlace.java
  src/main/java/emissary/util/ConstructorLookupCache.java
Labels: tech-debt

#1106 removing obsolete myKey value from SessionProducer constructor
  src/main/java/emissary/parser/SessionProducer.java
  src/main/java/emissary/pickup/PickUpPlace.java
Labels: integration

#1085 refresh :: add monitoring code to detect config changes
  src/main/java/emissary/place/ServiceProviderRefreshablePlace.java
  src/main/java/emissary/server/EmissaryServer.java
Labels: feature, activation

#1114 turn on PMD enforcement for all violations
  pom.xml
  src/main/java/emissary/parser/SessionProducer.java
Labels: tech-debt

#1119 add ignored suffix values for versions plugin
  pom.xml
Labels: BPD

#1113 ci :: java 21
  .github/workflows/maven-ci.yml
Labels: CI/CD

#1124 tests :: tweak answer schema
  src/test/resources/emissary/test/core/schemas/answers.xsd
Labels: test-only

#1120 dependencies: bump dropwizard metrics from 4.2.25 to 4.2.30
  pom.xml
Labels: dependencies

#1123 dependencies: bump junit to 5.12.2 and mockito to 5.17.0
  pom.xml
Labels: dependencies

#1122 dependencies: bump jackson from 2.15.2 to 2.18.3
  pom.xml
Labels: dependencies

#1129 dependencies: bump commons-io from 2.17.0 to 2.19.0
  pom.xml
Labels: dependencies

#1128 dependencies: bump commons-codec from 1.16.0 to 1.18.0
  pom.xml
Labels: dependencies

#1127 dependencies: bump commons-exec from 1.3 to 1.4.0
  pom.xml
Labels: dependencies

#1126 dependencies: bump restrict-imports-enforcer-rule plugin from 2.3.1 to 2.6.1
  pom.xml
Labels: dependencies

#1125 update to jaxb runtime 4.x
  pom.xml
Labels: dependencies, integration

#1131 add SessionProducer constructor that defaults to null initialForm
  src/main/java/emissary/parser/SessionProducer.java
  src/main/java/emissary/pickup/PickUpPlace.java
Labels: tech-debt

#1133 Added InputStreamChannelFactory optional support for bounded sizing
  src/main/java/emissary/core/channels/InputStreamChannelFactory.java
  src/test/java/emissary/core/channels/InputStreamChannelFactoryTest.java
Labels: improvement

#1060 add dropoff event to ObjectTracing
  src/main/java/emissary/output/filter/AbstractRollableFilter.java
  src/main/java/emissary/spi/EmissaryObjectTracingProvider.java
  src/main/java/emissary/spi/ObjectTracing.java
  src/main/java/emissary/spi/ObjectTracingService.java
  src/main/resources/emissary/output/filter/JsonOutputFilter.cfg
Labels: enhancement
